package com.yannuo.dgcanteen.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CARD_PAY".
*/
public class CardPayDao extends AbstractDao<CardPay, Long> {

    public static final String TABLENAME = "CARD_PAY";

    /**
     * Properties of entity CardPay.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Campus_id = new Property(1, String.class, "campus_id", false, "CAMPUS_ID");
        public final static Property Corp_id = new Property(2, String.class, "corp_id", false, "CORP_ID");
        public final static Property Txcode = new Property(3, String.class, "txcode", false, "TXCODE");
        public final static Property Business_id = new Property(4, String.class, "business_id", false, "BUSINESS_ID");
        public final static Property Vpos_id = new Property(5, String.class, "vpos_id", false, "VPOS_ID");
        public final static Property Payment = new Property(6, String.class, "payment", false, "PAYMENT");
        public final static Property Actual_payment = new Property(7, String.class, "actual_payment", false, "ACTUAL_PAYMENT");
        public final static Property Coupon_info = new Property(8, String.class, "coupon_info", false, "COUPON_INFO");
        public final static Property Offline = new Property(9, String.class, "offline", false, "OFFLINE");
        public final static Property Sign_time = new Property(10, String.class, "sign_time", false, "SIGN_TIME");
        public final static Property Acc_nos = new Property(11, String.class, "acc_nos", false, "ACC_NOS");
        public final static Property Card_id = new Property(12, String.class, "card_id", false, "CARD_ID");
        public final static Property Cust_id = new Property(13, String.class, "cust_id", false, "CUST_ID");
        public final static Property Order_id = new Property(14, String.class, "order_id", false, "ORDER_ID");
        public final static Property CipherUrl = new Property(15, String.class, "cipherUrl", false, "CIPHER_URL");
        public final static Property Up = new Property(16, boolean.class, "up", false, "UP");
    }

    private DaoSession daoSession;


    public CardPayDao(DaoConfig config) {
        super(config);
    }
    
    public CardPayDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CARD_PAY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CAMPUS_ID\" TEXT," + // 1: campus_id
                "\"CORP_ID\" TEXT," + // 2: corp_id
                "\"TXCODE\" TEXT," + // 3: txcode
                "\"BUSINESS_ID\" TEXT," + // 4: business_id
                "\"VPOS_ID\" TEXT," + // 5: vpos_id
                "\"PAYMENT\" TEXT," + // 6: payment
                "\"ACTUAL_PAYMENT\" TEXT," + // 7: actual_payment
                "\"COUPON_INFO\" TEXT," + // 8: coupon_info
                "\"OFFLINE\" TEXT," + // 9: offline
                "\"SIGN_TIME\" TEXT," + // 10: sign_time
                "\"ACC_NOS\" TEXT," + // 11: acc_nos
                "\"CARD_ID\" TEXT," + // 12: card_id
                "\"CUST_ID\" TEXT," + // 13: cust_id
                "\"ORDER_ID\" TEXT," + // 14: order_id
                "\"CIPHER_URL\" TEXT," + // 15: cipherUrl
                "\"UP\" INTEGER NOT NULL );"); // 16: up
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CARD_PAY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CardPay entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String campus_id = entity.getCampus_id();
        if (campus_id != null) {
            stmt.bindString(2, campus_id);
        }
 
        String corp_id = entity.getCorp_id();
        if (corp_id != null) {
            stmt.bindString(3, corp_id);
        }
 
        String txcode = entity.getTxcode();
        if (txcode != null) {
            stmt.bindString(4, txcode);
        }
 
        String business_id = entity.getBusiness_id();
        if (business_id != null) {
            stmt.bindString(5, business_id);
        }
 
        String vpos_id = entity.getVpos_id();
        if (vpos_id != null) {
            stmt.bindString(6, vpos_id);
        }
 
        String payment = entity.getPayment();
        if (payment != null) {
            stmt.bindString(7, payment);
        }
 
        String actual_payment = entity.getActual_payment();
        if (actual_payment != null) {
            stmt.bindString(8, actual_payment);
        }
 
        String coupon_info = entity.getCoupon_info();
        if (coupon_info != null) {
            stmt.bindString(9, coupon_info);
        }
 
        String offline = entity.getOffline();
        if (offline != null) {
            stmt.bindString(10, offline);
        }
 
        String sign_time = entity.getSign_time();
        if (sign_time != null) {
            stmt.bindString(11, sign_time);
        }
 
        String acc_nos = entity.getAcc_nos();
        if (acc_nos != null) {
            stmt.bindString(12, acc_nos);
        }
 
        String card_id = entity.getCard_id();
        if (card_id != null) {
            stmt.bindString(13, card_id);
        }
 
        String cust_id = entity.getCust_id();
        if (cust_id != null) {
            stmt.bindString(14, cust_id);
        }
 
        String order_id = entity.getOrder_id();
        if (order_id != null) {
            stmt.bindString(15, order_id);
        }
 
        String cipherUrl = entity.getCipherUrl();
        if (cipherUrl != null) {
            stmt.bindString(16, cipherUrl);
        }
        stmt.bindLong(17, entity.getUp() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CardPay entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String campus_id = entity.getCampus_id();
        if (campus_id != null) {
            stmt.bindString(2, campus_id);
        }
 
        String corp_id = entity.getCorp_id();
        if (corp_id != null) {
            stmt.bindString(3, corp_id);
        }
 
        String txcode = entity.getTxcode();
        if (txcode != null) {
            stmt.bindString(4, txcode);
        }
 
        String business_id = entity.getBusiness_id();
        if (business_id != null) {
            stmt.bindString(5, business_id);
        }
 
        String vpos_id = entity.getVpos_id();
        if (vpos_id != null) {
            stmt.bindString(6, vpos_id);
        }
 
        String payment = entity.getPayment();
        if (payment != null) {
            stmt.bindString(7, payment);
        }
 
        String actual_payment = entity.getActual_payment();
        if (actual_payment != null) {
            stmt.bindString(8, actual_payment);
        }
 
        String coupon_info = entity.getCoupon_info();
        if (coupon_info != null) {
            stmt.bindString(9, coupon_info);
        }
 
        String offline = entity.getOffline();
        if (offline != null) {
            stmt.bindString(10, offline);
        }
 
        String sign_time = entity.getSign_time();
        if (sign_time != null) {
            stmt.bindString(11, sign_time);
        }
 
        String acc_nos = entity.getAcc_nos();
        if (acc_nos != null) {
            stmt.bindString(12, acc_nos);
        }
 
        String card_id = entity.getCard_id();
        if (card_id != null) {
            stmt.bindString(13, card_id);
        }
 
        String cust_id = entity.getCust_id();
        if (cust_id != null) {
            stmt.bindString(14, cust_id);
        }
 
        String order_id = entity.getOrder_id();
        if (order_id != null) {
            stmt.bindString(15, order_id);
        }
 
        String cipherUrl = entity.getCipherUrl();
        if (cipherUrl != null) {
            stmt.bindString(16, cipherUrl);
        }
        stmt.bindLong(17, entity.getUp() ? 1L: 0L);
    }

    @Override
    protected final void attachEntity(CardPay entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CardPay readEntity(Cursor cursor, int offset) {
        CardPay entity = new CardPay( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // campus_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // corp_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // txcode
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // business_id
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // vpos_id
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // payment
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // actual_payment
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // coupon_info
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // offline
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // sign_time
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // acc_nos
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // card_id
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // cust_id
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // order_id
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // cipherUrl
            cursor.getShort(offset + 16) != 0 // up
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CardPay entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCampus_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCorp_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTxcode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBusiness_id(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setVpos_id(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPayment(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setActual_payment(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCoupon_info(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setOffline(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setSign_time(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setAcc_nos(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setCard_id(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setCust_id(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setOrder_id(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setCipherUrl(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setUp(cursor.getShort(offset + 16) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CardPay entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CardPay entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CardPay entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
