package com.yannuo.dgcanteen.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yannuo.dgcanteen.dao.DishTable;
import com.yannuo.dgcanteen.dao.MealTable;
import com.yannuo.dgcanteen.dao.ProductsTable;

import com.yannuo.dgcanteen.dao.DishTableDao;
import com.yannuo.dgcanteen.dao.MealTableDao;
import com.yannuo.dgcanteen.dao.ProductsTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dishTableDaoConfig;
    private final DaoConfig mealTableDaoConfig;
    private final DaoConfig productsTableDaoConfig;

    private final DishTableDao dishTableDao;
    private final MealTableDao mealTableDao;
    private final ProductsTableDao productsTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dishTableDaoConfig = daoConfigMap.get(DishTableDao.class).clone();
        dishTableDaoConfig.initIdentityScope(type);

        mealTableDaoConfig = daoConfigMap.get(MealTableDao.class).clone();
        mealTableDaoConfig.initIdentityScope(type);

        productsTableDaoConfig = daoConfigMap.get(ProductsTableDao.class).clone();
        productsTableDaoConfig.initIdentityScope(type);

        dishTableDao = new DishTableDao(dishTableDaoConfig, this);
        mealTableDao = new MealTableDao(mealTableDaoConfig, this);
        productsTableDao = new ProductsTableDao(productsTableDaoConfig, this);

        registerDao(DishTable.class, dishTableDao);
        registerDao(MealTable.class, mealTableDao);
        registerDao(ProductsTable.class, productsTableDao);
    }
    
    public void clear() {
        dishTableDaoConfig.clearIdentityScope();
        mealTableDaoConfig.clearIdentityScope();
        productsTableDaoConfig.clearIdentityScope();
    }

    public DishTableDao getDishTableDao() {
        return dishTableDao;
    }

    public MealTableDao getMealTableDao() {
        return mealTableDao;
    }

    public ProductsTableDao getProductsTableDao() {
        return productsTableDao;
    }

}
