package com.yannuo.dgcanteen.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yannuo.dgcanteen.dao.DishesTable;
import com.yannuo.dgcanteen.dao.MealTable;
import com.yannuo.dgcanteen.dao.OrderDishList;
import com.yannuo.dgcanteen.dao.OwnOrder;

import com.yannuo.dgcanteen.dao.DishesTableDao;
import com.yannuo.dgcanteen.dao.MealTableDao;
import com.yannuo.dgcanteen.dao.OrderDishListDao;
import com.yannuo.dgcanteen.dao.OwnOrderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dishesTableDaoConfig;
    private final DaoConfig mealTableDaoConfig;
    private final DaoConfig orderDishListDaoConfig;
    private final DaoConfig ownOrderDaoConfig;

    private final DishesTableDao dishesTableDao;
    private final MealTableDao mealTableDao;
    private final OrderDishListDao orderDishListDao;
    private final OwnOrderDao ownOrderDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dishesTableDaoConfig = daoConfigMap.get(DishesTableDao.class).clone();
        dishesTableDaoConfig.initIdentityScope(type);

        mealTableDaoConfig = daoConfigMap.get(MealTableDao.class).clone();
        mealTableDaoConfig.initIdentityScope(type);

        orderDishListDaoConfig = daoConfigMap.get(OrderDishListDao.class).clone();
        orderDishListDaoConfig.initIdentityScope(type);

        ownOrderDaoConfig = daoConfigMap.get(OwnOrderDao.class).clone();
        ownOrderDaoConfig.initIdentityScope(type);

        dishesTableDao = new DishesTableDao(dishesTableDaoConfig, this);
        mealTableDao = new MealTableDao(mealTableDaoConfig, this);
        orderDishListDao = new OrderDishListDao(orderDishListDaoConfig, this);
        ownOrderDao = new OwnOrderDao(ownOrderDaoConfig, this);

        registerDao(DishesTable.class, dishesTableDao);
        registerDao(MealTable.class, mealTableDao);
        registerDao(OrderDishList.class, orderDishListDao);
        registerDao(OwnOrder.class, ownOrderDao);
    }
    
    public void clear() {
        dishesTableDaoConfig.clearIdentityScope();
        mealTableDaoConfig.clearIdentityScope();
        orderDishListDaoConfig.clearIdentityScope();
        ownOrderDaoConfig.clearIdentityScope();
    }

    public DishesTableDao getDishesTableDao() {
        return dishesTableDao;
    }

    public MealTableDao getMealTableDao() {
        return mealTableDao;
    }

    public OrderDishListDao getOrderDishListDao() {
        return orderDishListDao;
    }

    public OwnOrderDao getOwnOrderDao() {
        return ownOrderDao;
    }

}
