package com.yannuo.dgcanteen.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productsTableDaoConfig;

    private final ProductsTableDao productsTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productsTableDaoConfig = daoConfigMap.get(ProductsTableDao.class).clone();
        productsTableDaoConfig.initIdentityScope(type);

        productsTableDao = new ProductsTableDao(productsTableDaoConfig, this);

        registerDao(ProductsTable.class, productsTableDao);
    }
    
    public void clear() {
        productsTableDaoConfig.clearIdentityScope();
    }

    public ProductsTableDao getProductsTableDao() {
        return productsTableDao;
    }

}
