package com.yannuo.dgcanteen.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DISH_TABLE".
*/
public class DishTableDao extends AbstractDao<DishTable, Void> {

    public static final String TABLENAME = "DISH_TABLE";

    /**
     * Properties of entity DishTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UserId = new Property(0, String.class, "userId", false, "USER_ID");
        public final static Property BusinessId = new Property(1, Long.class, "businessId", false, "BUSINESS_ID");
        public final static Property DishesId = new Property(2, String.class, "dishesId", false, "DISHES_ID");
        public final static Property DishesName = new Property(3, String.class, "dishesName", false, "DISHES_NAME");
        public final static Property WindowId = new Property(4, String.class, "windowId", false, "WINDOW_ID");
        public final static Property MealID = new Property(5, String.class, "mealID", false, "MEAL_ID");
        public final static Property Price = new Property(6, Double.class, "price", false, "PRICE");
        public final static Property Unit = new Property(7, String.class, "unit", false, "UNIT");
        public final static Property ImgUrl = new Property(8, String.class, "imgUrl", false, "IMG_URL");
        public final static Property Status = new Property(9, String.class, "status", false, "STATUS");
    }


    public DishTableDao(DaoConfig config) {
        super(config);
    }
    
    public DishTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DISH_TABLE\" (" + //
                "\"USER_ID\" TEXT," + // 0: userId
                "\"BUSINESS_ID\" INTEGER," + // 1: businessId
                "\"DISHES_ID\" TEXT NOT NULL ," + // 2: dishesId
                "\"DISHES_NAME\" TEXT NOT NULL ," + // 3: dishesName
                "\"WINDOW_ID\" TEXT NOT NULL ," + // 4: windowId
                "\"MEAL_ID\" TEXT NOT NULL ," + // 5: mealID
                "\"PRICE\" REAL NOT NULL ," + // 6: price
                "\"UNIT\" TEXT," + // 7: unit
                "\"IMG_URL\" TEXT," + // 8: imgUrl
                "\"STATUS\" TEXT);"); // 9: status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DISH_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DishTable entity) {
        stmt.clearBindings();
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(1, userId);
        }
 
        Long businessId = entity.getBusinessId();
        if (businessId != null) {
            stmt.bindLong(2, businessId);
        }
        stmt.bindString(3, entity.getDishesId());
        stmt.bindString(4, entity.getDishesName());
        stmt.bindString(5, entity.getWindowId());
        stmt.bindString(6, entity.getMealID());
        stmt.bindDouble(7, entity.getPrice());
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(8, unit);
        }
 
        String imgUrl = entity.getImgUrl();
        if (imgUrl != null) {
            stmt.bindString(9, imgUrl);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(10, status);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DishTable entity) {
        stmt.clearBindings();
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(1, userId);
        }
 
        Long businessId = entity.getBusinessId();
        if (businessId != null) {
            stmt.bindLong(2, businessId);
        }
        stmt.bindString(3, entity.getDishesId());
        stmt.bindString(4, entity.getDishesName());
        stmt.bindString(5, entity.getWindowId());
        stmt.bindString(6, entity.getMealID());
        stmt.bindDouble(7, entity.getPrice());
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(8, unit);
        }
 
        String imgUrl = entity.getImgUrl();
        if (imgUrl != null) {
            stmt.bindString(9, imgUrl);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(10, status);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public DishTable readEntity(Cursor cursor, int offset) {
        DishTable entity = new DishTable( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // userId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // businessId
            cursor.getString(offset + 2), // dishesId
            cursor.getString(offset + 3), // dishesName
            cursor.getString(offset + 4), // windowId
            cursor.getString(offset + 5), // mealID
            cursor.getDouble(offset + 6), // price
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // unit
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // imgUrl
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DishTable entity, int offset) {
        entity.setUserId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setBusinessId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setDishesId(cursor.getString(offset + 2));
        entity.setDishesName(cursor.getString(offset + 3));
        entity.setWindowId(cursor.getString(offset + 4));
        entity.setMealID(cursor.getString(offset + 5));
        entity.setPrice(cursor.getDouble(offset + 6));
        entity.setUnit(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setImgUrl(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setStatus(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(DishTable entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(DishTable entity) {
        return null;
    }

    @Override
    public boolean hasKey(DishTable entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
