package com.yannuo.dgcanteen.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEAL_TABLE".
*/
public class MealTableDao extends AbstractDao<MealTable, Void> {

    public static final String TABLENAME = "MEAL_TABLE";

    /**
     * Properties of entity MealTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UserId = new Property(0, String.class, "userId", false, "USER_ID");
        public final static Property BusinessID = new Property(1, Long.class, "businessID", false, "BUSINESS_ID");
        public final static Property WindowID = new Property(2, String.class, "windowID", false, "WINDOW_ID");
        public final static Property MealID = new Property(3, int.class, "mealID", false, "MEAL_ID");
        public final static Property MealName = new Property(4, String.class, "mealName", false, "MEAL_NAME");
        public final static Property StartTime = new Property(5, java.util.Date.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(6, java.util.Date.class, "endTime", false, "END_TIME");
    }


    public MealTableDao(DaoConfig config) {
        super(config);
    }
    
    public MealTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEAL_TABLE\" (" + //
                "\"USER_ID\" TEXT," + // 0: userId
                "\"BUSINESS_ID\" INTEGER," + // 1: businessID
                "\"WINDOW_ID\" TEXT NOT NULL ," + // 2: windowID
                "\"MEAL_ID\" INTEGER NOT NULL ," + // 3: mealID
                "\"MEAL_NAME\" TEXT NOT NULL ," + // 4: mealName
                "\"START_TIME\" INTEGER," + // 5: startTime
                "\"END_TIME\" INTEGER);"); // 6: endTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEAL_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MealTable entity) {
        stmt.clearBindings();
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(1, userId);
        }
 
        Long businessID = entity.getBusinessID();
        if (businessID != null) {
            stmt.bindLong(2, businessID);
        }
        stmt.bindString(3, entity.getWindowID());
        stmt.bindLong(4, entity.getMealID());
        stmt.bindString(5, entity.getMealName());
 
        java.util.Date startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(6, startTime.getTime());
        }
 
        java.util.Date endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(7, endTime.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MealTable entity) {
        stmt.clearBindings();
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(1, userId);
        }
 
        Long businessID = entity.getBusinessID();
        if (businessID != null) {
            stmt.bindLong(2, businessID);
        }
        stmt.bindString(3, entity.getWindowID());
        stmt.bindLong(4, entity.getMealID());
        stmt.bindString(5, entity.getMealName());
 
        java.util.Date startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(6, startTime.getTime());
        }
 
        java.util.Date endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(7, endTime.getTime());
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public MealTable readEntity(Cursor cursor, int offset) {
        MealTable entity = new MealTable( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // userId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // businessID
            cursor.getString(offset + 2), // windowID
            cursor.getInt(offset + 3), // mealID
            cursor.getString(offset + 4), // mealName
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // startTime
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)) // endTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MealTable entity, int offset) {
        entity.setUserId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setBusinessID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setWindowID(cursor.getString(offset + 2));
        entity.setMealID(cursor.getInt(offset + 3));
        entity.setMealName(cursor.getString(offset + 4));
        entity.setStartTime(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setEndTime(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(MealTable entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(MealTable entity) {
        return null;
    }

    @Override
    public boolean hasKey(MealTable entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
