package com.yannuo.dgcanteen.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "OFF_LINE_TABLE".
*/
public class OffLineTableDao extends AbstractDao<OffLineTable, Long> {

    public static final String TABLENAME = "OFF_LINE_TABLE";

    /**
     * Properties of entity OffLineTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CAMPUS_ID = new Property(1, String.class, "CAMPUS_ID", false, "CAMPUS__ID");
        public final static Property CORP_ID = new Property(2, String.class, "CORP_ID", false, "CORP__ID");
        public final static Property TXCODE = new Property(3, String.class, "TXCODE", false, "TXCODE");
        public final static Property CcbSafeParam = new Property(4, String.class, "ccbSafeParam", false, "CCB_SAFE_PARAM");
        public final static Property BUSINESS_ID = new Property(5, String.class, "BUSINESS_ID", false, "BUSINESS__ID");
        public final static Property VPOS_ID = new Property(6, String.class, "VPOS_ID", false, "VPOS__ID");
        public final static Property PAYMENT = new Property(7, String.class, "PAYMENT", false, "PAYMENT");
        public final static Property ACTUAL_PAYMENT = new Property(8, String.class, "ACTUAL_PAYMENT", false, "ACTUAL__PAYMENT");
        public final static Property COUPON_INFO = new Property(9, String.class, "COUPON_INFO", false, "COUPON__INFO");
        public final static Property ACC_NOS = new Property(10, String.class, "ACC_NOS", false, "ACC__NOS");
        public final static Property QR_CODE = new Property(11, String.class, "QR_CODE", false, "QR__CODE");
        public final static Property CUST_ID = new Property(12, String.class, "CUST_ID", false, "CUST__ID");
        public final static Property ORDER_ID = new Property(13, String.class, "ORDER_ID", false, "ORDER__ID");
        public final static Property OFFLINE = new Property(14, String.class, "OFFLINE", false, "OFFLINE");
        public final static Property SIGN_TIME = new Property(15, String.class, "SIGN_TIME", false, "SIGN__TIME");
        public final static Property DecryptionCode = new Property(16, String.class, "decryptionCode", false, "DECRYPTION_CODE");
        public final static Property PostTag = new Property(17, boolean.class, "postTag", false, "POST_TAG");
    }

    private DaoSession daoSession;


    public OffLineTableDao(DaoConfig config) {
        super(config);
    }
    
    public OffLineTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"OFF_LINE_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CAMPUS__ID\" TEXT NOT NULL ," + // 1: CAMPUS_ID
                "\"CORP__ID\" TEXT NOT NULL ," + // 2: CORP_ID
                "\"TXCODE\" TEXT NOT NULL ," + // 3: TXCODE
                "\"CCB_SAFE_PARAM\" TEXT NOT NULL ," + // 4: ccbSafeParam
                "\"BUSINESS__ID\" TEXT NOT NULL ," + // 5: BUSINESS_ID
                "\"VPOS__ID\" TEXT NOT NULL ," + // 6: VPOS_ID
                "\"PAYMENT\" TEXT NOT NULL ," + // 7: PAYMENT
                "\"ACTUAL__PAYMENT\" TEXT NOT NULL ," + // 8: ACTUAL_PAYMENT
                "\"COUPON__INFO\" TEXT," + // 9: COUPON_INFO
                "\"ACC__NOS\" TEXT," + // 10: ACC_NOS
                "\"QR__CODE\" TEXT NOT NULL ," + // 11: QR_CODE
                "\"CUST__ID\" TEXT," + // 12: CUST_ID
                "\"ORDER__ID\" TEXT NOT NULL UNIQUE ," + // 13: ORDER_ID
                "\"OFFLINE\" TEXT NOT NULL ," + // 14: OFFLINE
                "\"SIGN__TIME\" TEXT NOT NULL ," + // 15: SIGN_TIME
                "\"DECRYPTION_CODE\" TEXT NOT NULL ," + // 16: decryptionCode
                "\"POST_TAG\" INTEGER NOT NULL );"); // 17: postTag
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"OFF_LINE_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OffLineTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getCAMPUS_ID());
        stmt.bindString(3, entity.getCORP_ID());
        stmt.bindString(4, entity.getTXCODE());
        stmt.bindString(5, entity.getCcbSafeParam());
        stmt.bindString(6, entity.getBUSINESS_ID());
        stmt.bindString(7, entity.getVPOS_ID());
        stmt.bindString(8, entity.getPAYMENT());
        stmt.bindString(9, entity.getACTUAL_PAYMENT());
 
        String COUPON_INFO = entity.getCOUPON_INFO();
        if (COUPON_INFO != null) {
            stmt.bindString(10, COUPON_INFO);
        }
 
        String ACC_NOS = entity.getACC_NOS();
        if (ACC_NOS != null) {
            stmt.bindString(11, ACC_NOS);
        }
        stmt.bindString(12, entity.getQR_CODE());
 
        String CUST_ID = entity.getCUST_ID();
        if (CUST_ID != null) {
            stmt.bindString(13, CUST_ID);
        }
        stmt.bindString(14, entity.getORDER_ID());
        stmt.bindString(15, entity.getOFFLINE());
        stmt.bindString(16, entity.getSIGN_TIME());
        stmt.bindString(17, entity.getDecryptionCode());
        stmt.bindLong(18, entity.getPostTag() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OffLineTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getCAMPUS_ID());
        stmt.bindString(3, entity.getCORP_ID());
        stmt.bindString(4, entity.getTXCODE());
        stmt.bindString(5, entity.getCcbSafeParam());
        stmt.bindString(6, entity.getBUSINESS_ID());
        stmt.bindString(7, entity.getVPOS_ID());
        stmt.bindString(8, entity.getPAYMENT());
        stmt.bindString(9, entity.getACTUAL_PAYMENT());
 
        String COUPON_INFO = entity.getCOUPON_INFO();
        if (COUPON_INFO != null) {
            stmt.bindString(10, COUPON_INFO);
        }
 
        String ACC_NOS = entity.getACC_NOS();
        if (ACC_NOS != null) {
            stmt.bindString(11, ACC_NOS);
        }
        stmt.bindString(12, entity.getQR_CODE());
 
        String CUST_ID = entity.getCUST_ID();
        if (CUST_ID != null) {
            stmt.bindString(13, CUST_ID);
        }
        stmt.bindString(14, entity.getORDER_ID());
        stmt.bindString(15, entity.getOFFLINE());
        stmt.bindString(16, entity.getSIGN_TIME());
        stmt.bindString(17, entity.getDecryptionCode());
        stmt.bindLong(18, entity.getPostTag() ? 1L: 0L);
    }

    @Override
    protected final void attachEntity(OffLineTable entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OffLineTable readEntity(Cursor cursor, int offset) {
        OffLineTable entity = new OffLineTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // CAMPUS_ID
            cursor.getString(offset + 2), // CORP_ID
            cursor.getString(offset + 3), // TXCODE
            cursor.getString(offset + 4), // ccbSafeParam
            cursor.getString(offset + 5), // BUSINESS_ID
            cursor.getString(offset + 6), // VPOS_ID
            cursor.getString(offset + 7), // PAYMENT
            cursor.getString(offset + 8), // ACTUAL_PAYMENT
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // COUPON_INFO
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // ACC_NOS
            cursor.getString(offset + 11), // QR_CODE
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // CUST_ID
            cursor.getString(offset + 13), // ORDER_ID
            cursor.getString(offset + 14), // OFFLINE
            cursor.getString(offset + 15), // SIGN_TIME
            cursor.getString(offset + 16), // decryptionCode
            cursor.getShort(offset + 17) != 0 // postTag
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OffLineTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCAMPUS_ID(cursor.getString(offset + 1));
        entity.setCORP_ID(cursor.getString(offset + 2));
        entity.setTXCODE(cursor.getString(offset + 3));
        entity.setCcbSafeParam(cursor.getString(offset + 4));
        entity.setBUSINESS_ID(cursor.getString(offset + 5));
        entity.setVPOS_ID(cursor.getString(offset + 6));
        entity.setPAYMENT(cursor.getString(offset + 7));
        entity.setACTUAL_PAYMENT(cursor.getString(offset + 8));
        entity.setCOUPON_INFO(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setACC_NOS(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setQR_CODE(cursor.getString(offset + 11));
        entity.setCUST_ID(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setORDER_ID(cursor.getString(offset + 13));
        entity.setOFFLINE(cursor.getString(offset + 14));
        entity.setSIGN_TIME(cursor.getString(offset + 15));
        entity.setDecryptionCode(cursor.getString(offset + 16));
        entity.setPostTag(cursor.getShort(offset + 17) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OffLineTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OffLineTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OffLineTable entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
