package com.yannuo.dgcanteen.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ORDER_DISH_LIST".
*/
public class OrderDishListDao extends AbstractDao<OrderDishList, Long> {

    public static final String TABLENAME = "ORDER_DISH_LIST";

    /**
     * Properties of entity OrderDishList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Orderid = new Property(1, Long.class, "orderid", false, "ORDERID");
        public final static Property DishesId = new Property(2, String.class, "dishesId", false, "DISHES_ID");
        public final static Property DishesName = new Property(3, String.class, "dishesName", false, "DISHES_NAME");
        public final static Property DishesNumber = new Property(4, int.class, "dishesNumber", false, "DISHES_NUMBER");
        public final static Property DishesPrice = new Property(5, double.class, "dishesPrice", false, "DISHES_PRICE");
    }

    private DaoSession daoSession;

    private Query<OrderDishList> ownOrder_PaymentDishesListQuery;

    public OrderDishListDao(DaoConfig config) {
        super(config);
    }
    
    public OrderDishListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ORDER_DISH_LIST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ORDERID\" INTEGER," + // 1: orderid
                "\"DISHES_ID\" TEXT," + // 2: dishesId
                "\"DISHES_NAME\" TEXT," + // 3: dishesName
                "\"DISHES_NUMBER\" INTEGER NOT NULL ," + // 4: dishesNumber
                "\"DISHES_PRICE\" REAL NOT NULL );"); // 5: dishesPrice
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ORDER_DISH_LIST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OrderDishList entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long orderid = entity.getOrderid();
        if (orderid != null) {
            stmt.bindLong(2, orderid);
        }
 
        String dishesId = entity.getDishesId();
        if (dishesId != null) {
            stmt.bindString(3, dishesId);
        }
 
        String dishesName = entity.getDishesName();
        if (dishesName != null) {
            stmt.bindString(4, dishesName);
        }
        stmt.bindLong(5, entity.getDishesNumber());
        stmt.bindDouble(6, entity.getDishesPrice());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OrderDishList entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long orderid = entity.getOrderid();
        if (orderid != null) {
            stmt.bindLong(2, orderid);
        }
 
        String dishesId = entity.getDishesId();
        if (dishesId != null) {
            stmt.bindString(3, dishesId);
        }
 
        String dishesName = entity.getDishesName();
        if (dishesName != null) {
            stmt.bindString(4, dishesName);
        }
        stmt.bindLong(5, entity.getDishesNumber());
        stmt.bindDouble(6, entity.getDishesPrice());
    }

    @Override
    protected final void attachEntity(OrderDishList entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OrderDishList readEntity(Cursor cursor, int offset) {
        OrderDishList entity = new OrderDishList( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // orderid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // dishesId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // dishesName
            cursor.getInt(offset + 4), // dishesNumber
            cursor.getDouble(offset + 5) // dishesPrice
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OrderDishList entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOrderid(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setDishesId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDishesName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDishesNumber(cursor.getInt(offset + 4));
        entity.setDishesPrice(cursor.getDouble(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OrderDishList entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OrderDishList entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OrderDishList entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "paymentDishesList" to-many relationship of OwnOrder. */
    public List<OrderDishList> _queryOwnOrder_PaymentDishesList(Long orderid) {
        synchronized (this) {
            if (ownOrder_PaymentDishesListQuery == null) {
                QueryBuilder<OrderDishList> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Orderid.eq(null));
                ownOrder_PaymentDishesListQuery = queryBuilder.build();
            }
        }
        Query<OrderDishList> query = ownOrder_PaymentDishesListQuery.forCurrentThread();
        query.setParameter(0, orderid);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getOwnOrderDao().getAllColumns());
            builder.append(" FROM ORDER_DISH_LIST T");
            builder.append(" LEFT JOIN OWN_ORDER T0 ON T.\"ORDERID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected OrderDishList loadCurrentDeep(Cursor cursor, boolean lock) {
        OrderDishList entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        OwnOrder order = loadCurrentOther(daoSession.getOwnOrderDao(), cursor, offset);
        entity.setOrder(order);

        return entity;    
    }

    public OrderDishList loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<OrderDishList> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<OrderDishList> list = new ArrayList<OrderDishList>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<OrderDishList> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<OrderDishList> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
