package com.yannuo.dgcanteen.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PERSONS".
*/
public class PersonsDao extends AbstractDao<Persons, Long> {

    public static final String TABLENAME = "PERSONS";

    /**
     * Properties of entity Persons.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CardId = new Property(1, String.class, "cardId", false, "CARD_ID");
        public final static Property CustId = new Property(2, String.class, "custId", false, "CUST_ID");
        public final static Property Grade = new Property(3, String.class, "grade", false, "GRADE");
        public final static Property PersonName = new Property(4, String.class, "personName", false, "PERSON_NAME");
        public final static Property PersonNumber = new Property(5, String.class, "personNumber", false, "PERSON_NUMBER");
        public final static Property UserClass = new Property(6, String.class, "userClass", false, "USER_CLASS");
    }


    public PersonsDao(DaoConfig config) {
        super(config);
    }
    
    public PersonsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PERSONS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CARD_ID\" TEXT," + // 1: cardId
                "\"CUST_ID\" TEXT UNIQUE ," + // 2: custId
                "\"GRADE\" TEXT," + // 3: grade
                "\"PERSON_NAME\" TEXT," + // 4: personName
                "\"PERSON_NUMBER\" TEXT," + // 5: personNumber
                "\"USER_CLASS\" TEXT);"); // 6: userClass
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PERSONS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Persons entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String cardId = entity.getCardId();
        if (cardId != null) {
            stmt.bindString(2, cardId);
        }
 
        String custId = entity.getCustId();
        if (custId != null) {
            stmt.bindString(3, custId);
        }
 
        String grade = entity.getGrade();
        if (grade != null) {
            stmt.bindString(4, grade);
        }
 
        String personName = entity.getPersonName();
        if (personName != null) {
            stmt.bindString(5, personName);
        }
 
        String personNumber = entity.getPersonNumber();
        if (personNumber != null) {
            stmt.bindString(6, personNumber);
        }
 
        String userClass = entity.getUserClass();
        if (userClass != null) {
            stmt.bindString(7, userClass);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Persons entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String cardId = entity.getCardId();
        if (cardId != null) {
            stmt.bindString(2, cardId);
        }
 
        String custId = entity.getCustId();
        if (custId != null) {
            stmt.bindString(3, custId);
        }
 
        String grade = entity.getGrade();
        if (grade != null) {
            stmt.bindString(4, grade);
        }
 
        String personName = entity.getPersonName();
        if (personName != null) {
            stmt.bindString(5, personName);
        }
 
        String personNumber = entity.getPersonNumber();
        if (personNumber != null) {
            stmt.bindString(6, personNumber);
        }
 
        String userClass = entity.getUserClass();
        if (userClass != null) {
            stmt.bindString(7, userClass);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Persons readEntity(Cursor cursor, int offset) {
        Persons entity = new Persons( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // cardId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // custId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // grade
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // personName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // personNumber
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // userClass
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Persons entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCardId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCustId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGrade(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPersonName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPersonNumber(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUserClass(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Persons entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Persons entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Persons entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
