package com.yannuo.dgcanteen.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRODUCTS_TABLE".
*/
public class ProductsTableDao extends AbstractDao<ProductsTable, Long> {

    public static final String TABLENAME = "PRODUCTS_TABLE";

    /**
     * Properties of entity ProductsTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BarCode = new Property(1, String.class, "barCode", false, "BAR_CODE");
        public final static Property PName = new Property(2, String.class, "pName", false, "P_NAME");
        public final static Property PMoney = new Property(3, String.class, "pMoney", false, "P_MONEY");
        public final static Property Type = new Property(4, String.class, "type", false, "TYPE");
        public final static Property PictureName = new Property(5, String.class, "pictureName", false, "PICTURE_NAME");
    }


    public ProductsTableDao(DaoConfig config) {
        super(config);
    }
    
    public ProductsTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRODUCTS_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"BAR_CODE\" TEXT UNIQUE ," + // 1: barCode
                "\"P_NAME\" TEXT," + // 2: pName
                "\"P_MONEY\" TEXT NOT NULL ," + // 3: pMoney
                "\"TYPE\" TEXT NOT NULL ," + // 4: type
                "\"PICTURE_NAME\" TEXT);"); // 5: pictureName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRODUCTS_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ProductsTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String barCode = entity.getBarCode();
        if (barCode != null) {
            stmt.bindString(2, barCode);
        }
 
        String pName = entity.getPName();
        if (pName != null) {
            stmt.bindString(3, pName);
        }
        stmt.bindString(4, entity.getPMoney());
        stmt.bindString(5, entity.getType());
 
        String pictureName = entity.getPictureName();
        if (pictureName != null) {
            stmt.bindString(6, pictureName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ProductsTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String barCode = entity.getBarCode();
        if (barCode != null) {
            stmt.bindString(2, barCode);
        }
 
        String pName = entity.getPName();
        if (pName != null) {
            stmt.bindString(3, pName);
        }
        stmt.bindString(4, entity.getPMoney());
        stmt.bindString(5, entity.getType());
 
        String pictureName = entity.getPictureName();
        if (pictureName != null) {
            stmt.bindString(6, pictureName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ProductsTable readEntity(Cursor cursor, int offset) {
        ProductsTable entity = new ProductsTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // barCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // pName
            cursor.getString(offset + 3), // pMoney
            cursor.getString(offset + 4), // type
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // pictureName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ProductsTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBarCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPMoney(cursor.getString(offset + 3));
        entity.setType(cursor.getString(offset + 4));
        entity.setPictureName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ProductsTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ProductsTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ProductsTable entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
