package com.yannuo.dgcanteen.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VERIFY_DISHES".
*/
public class VerifyDishesDao extends AbstractDao<VerifyDishes, Long> {

    public static final String TABLENAME = "VERIFY_DISHES";

    /**
     * Properties of entity VerifyDishes.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PersonName = new Property(1, String.class, "personName", false, "PERSON_NAME");
        public final static Property Dish = new Property(2, String.class, "dish", false, "DISH");
        public final static Property Window = new Property(3, String.class, "window", false, "WINDOW");
        public final static Property UnDish = new Property(4, String.class, "unDish", false, "UN_DISH");
        public final static Property Time = new Property(5, String.class, "time", false, "TIME");
    }


    public VerifyDishesDao(DaoConfig config) {
        super(config);
    }
    
    public VerifyDishesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VERIFY_DISHES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PERSON_NAME\" TEXT," + // 1: personName
                "\"DISH\" TEXT," + // 2: dish
                "\"WINDOW\" TEXT," + // 3: window
                "\"UN_DISH\" TEXT," + // 4: unDish
                "\"TIME\" TEXT);"); // 5: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VERIFY_DISHES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VerifyDishes entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String personName = entity.getPersonName();
        if (personName != null) {
            stmt.bindString(2, personName);
        }
 
        String dish = entity.getDish();
        if (dish != null) {
            stmt.bindString(3, dish);
        }
 
        String window = entity.getWindow();
        if (window != null) {
            stmt.bindString(4, window);
        }
 
        String unDish = entity.getUnDish();
        if (unDish != null) {
            stmt.bindString(5, unDish);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VerifyDishes entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String personName = entity.getPersonName();
        if (personName != null) {
            stmt.bindString(2, personName);
        }
 
        String dish = entity.getDish();
        if (dish != null) {
            stmt.bindString(3, dish);
        }
 
        String window = entity.getWindow();
        if (window != null) {
            stmt.bindString(4, window);
        }
 
        String unDish = entity.getUnDish();
        if (unDish != null) {
            stmt.bindString(5, unDish);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VerifyDishes readEntity(Cursor cursor, int offset) {
        VerifyDishes entity = new VerifyDishes( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // personName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // dish
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // window
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // unDish
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VerifyDishes entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPersonName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDish(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setWindow(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUnDish(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VerifyDishes entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VerifyDishes entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VerifyDishes entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
