plugins {
    id 'com.android.application'
    id 'org.greenrobot.greendao'
    id 'org.jetbrains.kotlin.android'
    id("androidx.navigation.safeargs")
}
//apply plugin: 'kotlin-android'

def releaseTime() {
    return new Date().format("yyMMddHH", TimeZone.getDefault())
}

android {
    compileSdk 34
//    buildToolsVersion '30.0.0'
    defaultConfig {
        applicationId "com.yannuo.dgcanteen"
        minSdk 21
        //noinspection ExpiredTargetSdkVersion
        targetSdk 29
        versionCode 2
        versionName "1.0.1"

        ndk {
            // 设置支持的SO库架构
//            abiFilters 'arm64-v8a' //'armeabi', 'x86', 'armeabi-v7a', 'x86_64', 'arm64-v8a'
            abiFilters 'armeabi-v7a'
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    kotlinOptions { jvmTarget = 1.8 }

    packagingOptions {
        exclude 'META-INF/NOTICE.md'
        exclude 'META-INF/LICENSE.md'
    }

    signingConfigs {
        release {
            storeFile file('D:\\yannuo\\APK_KEY\\private_key\\payment.jks')
//            storeFile file('D:\\LLL\\android_double_creen-pack\\payment.jks')
            storePassword KEY_PASS
            keyAlias 'payment'
            keyPassword KEY_PASS
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            //配置签名
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility "1.8"
        targetCompatibility "1.8"
    }

    viewBinding {
        enabled = true
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
    ndkVersion '21.4.7075529'

    flavorDimensions "dgcanteen"
    //创建渠道
    productFlavors {
        //标准
        dg {
            versionCode 4
            versionName "1.0.4"
            buildConfigField "int", "CHANNEL", "0"
        }

        //手动输入金额版本
        input {
            versionCode 84
            versionName "1.8.4"
            buildConfigField "int", "CHANNEL", "1"
        }

    }

    // 打包后的文件名
    android.applicationVariants.all { variant ->
        variant.outputs.each { output ->
            if (variant.buildType.name == "release") output.outputFileName = "ccb_canteen-${variant.flavorName}-v${variant.versionName}-${releaseTime()}.apk"
            else output.outputFileName = "ccb_canteen-${variant.flavorName}-v${variant.versionName}-debug.apk"
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar','*.aar'])

    //建行食堂开发平台
    implementation files('libs/bcprov-jdk14-128.jar')
    implementation files('libs/COM.CCB.EnDecryptAlgorithm_v1.0_20120220.jar')

    implementation "androidx.navigation:navigation-fragment-ktx:2.5.3"
    implementation "androidx.navigation:navigation-ui-ktx:2.5.3"
    // Feature module Support
    implementation("androidx.navigation:navigation-dynamic-features-fragment:2.5.3")
    //Bugly
    implementation 'com.tencent.bugly:crashreport:latest.release' //latest.release指代最新版本

    implementation project(path: ':core')
    implementation project(path: ':file')
    implementation project(path: ':converter:gson')


    implementation 'com.airbnb.android:lottie:3.6.1'
    //GreenDao依赖库
    implementation 'org.greenrobot:greendao:3.3.0' // add library
    //greenDao升级帮助类
    implementation 'io.github.yuweiguocn:GreenDaoUpgradeHelper:v2.2.1'

    //okhttp3 日志拦截器
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.0'

    //retrofit2
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    //RxJava2
    implementation 'io.reactivex.rxjava2:rxjava:2.2.2'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.0'

    //mqtt
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.4'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

    // Kotlin + coroutines
    implementation("androidx.work:work-runtime-ktx:2.3.4")

    //recycleview 上拉刷新
//    implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.1.0")

    //glide
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
    //协程
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.9'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0'

    //二维码
    implementation 'com.google.zxing:core:3.3.0'

    //MMKV
    implementation 'com.tencent:mmkv:1.2.13'

    //EventBus
    implementation("org.greenrobot:eventbus:3.3.1")

    // 发送邮件（日志上送）
    implementation 'com.sun.mail:android-mail:1.6.7'
    implementation 'com.sun.mail:android-activation:1.6.7'

    implementation "androidx.core:core-ktx:1.5.0"
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

//    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.10'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    implementation 'androidx.core:core-ktx:1.6.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

}
greendao {
    schemaVersion 33 //指定数据库schema版本号，迁移等操作会用到;
    daoPackage 'com.yannuo.dgcanteen.greendao.dao' //dao的包名，包名默认是entity所在的包；
    targetGenDir 'src/main/java'//生成数据库文件的目录;
}