package com.yannuo.dgcanteen.greendao.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.yannuo.dgcanteen.greendao.entity.AccListTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ACC_LIST_TABLE".
*/
public class AccListTableDao extends AbstractDao<AccListTable, Long> {

    public static final String TABLENAME = "ACC_LIST_TABLE";

    /**
     * Properties of entity AccListTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AccId = new Property(1, Long.class, "accId", false, "ACC_ID");
        public final static Property ACC_BAL = new Property(2, String.class, "ACC_BAL", false, "ACC__BAL");
        public final static Property ACC_NO = new Property(3, String.class, "ACC_NO", false, "ACC__NO");
        public final static Property ACC_TYPE = new Property(4, String.class, "ACC_TYPE", false, "ACC__TYPE");
        public final static Property PAYMENT = new Property(5, String.class, "PAYMENT", false, "PAYMENT");
        public final static Property TRAN_ID = new Property(6, String.class, "TRAN_ID", false, "TRAN__ID");
    }

    private Query<AccListTable> payOrderTable_AccListQuery;

    public AccListTableDao(DaoConfig config) {
        super(config);
    }
    
    public AccListTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ACC_LIST_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ACC_ID\" INTEGER," + // 1: accId
                "\"ACC__BAL\" TEXT," + // 2: ACC_BAL
                "\"ACC__NO\" TEXT," + // 3: ACC_NO
                "\"ACC__TYPE\" TEXT," + // 4: ACC_TYPE
                "\"PAYMENT\" TEXT," + // 5: PAYMENT
                "\"TRAN__ID\" TEXT);"); // 6: TRAN_ID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACC_LIST_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AccListTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long accId = entity.getAccId();
        if (accId != null) {
            stmt.bindLong(2, accId);
        }
 
        String ACC_BAL = entity.getACC_BAL();
        if (ACC_BAL != null) {
            stmt.bindString(3, ACC_BAL);
        }
 
        String ACC_NO = entity.getACC_NO();
        if (ACC_NO != null) {
            stmt.bindString(4, ACC_NO);
        }
 
        String ACC_TYPE = entity.getACC_TYPE();
        if (ACC_TYPE != null) {
            stmt.bindString(5, ACC_TYPE);
        }
 
        String PAYMENT = entity.getPAYMENT();
        if (PAYMENT != null) {
            stmt.bindString(6, PAYMENT);
        }
 
        String TRAN_ID = entity.getTRAN_ID();
        if (TRAN_ID != null) {
            stmt.bindString(7, TRAN_ID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AccListTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long accId = entity.getAccId();
        if (accId != null) {
            stmt.bindLong(2, accId);
        }
 
        String ACC_BAL = entity.getACC_BAL();
        if (ACC_BAL != null) {
            stmt.bindString(3, ACC_BAL);
        }
 
        String ACC_NO = entity.getACC_NO();
        if (ACC_NO != null) {
            stmt.bindString(4, ACC_NO);
        }
 
        String ACC_TYPE = entity.getACC_TYPE();
        if (ACC_TYPE != null) {
            stmt.bindString(5, ACC_TYPE);
        }
 
        String PAYMENT = entity.getPAYMENT();
        if (PAYMENT != null) {
            stmt.bindString(6, PAYMENT);
        }
 
        String TRAN_ID = entity.getTRAN_ID();
        if (TRAN_ID != null) {
            stmt.bindString(7, TRAN_ID);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AccListTable readEntity(Cursor cursor, int offset) {
        AccListTable entity = new AccListTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // accId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ACC_BAL
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ACC_NO
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // ACC_TYPE
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // PAYMENT
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // TRAN_ID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AccListTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAccId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setACC_BAL(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setACC_NO(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setACC_TYPE(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPAYMENT(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTRAN_ID(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AccListTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AccListTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AccListTable entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "accList" to-many relationship of PayOrderTable. */
    public List<AccListTable> _queryPayOrderTable_AccList(Long accId) {
        synchronized (this) {
            if (payOrderTable_AccListQuery == null) {
                QueryBuilder<AccListTable> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AccId.eq(null));
                payOrderTable_AccListQuery = queryBuilder.build();
            }
        }
        Query<AccListTable> query = payOrderTable_AccListQuery.forCurrentThread();
        query.setParameter(0, accId);
        return query.list();
    }

}
