package com.yannuo.dgcanteen.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yannuo.dgcanteen.greendao.entity.CategoryTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CATEGORY_TABLE".
*/
public class CategoryTableDao extends AbstractDao<CategoryTable, Long> {

    public static final String TABLENAME = "CATEGORY_TABLE";

    /**
     * Properties of entity CategoryTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CategoryId = new Property(1, String.class, "categoryId", false, "CATEGORY_ID");
        public final static Property CategoryName = new Property(2, String.class, "categoryName", false, "CATEGORY_NAME");
        public final static Property Sort = new Property(3, String.class, "sort", false, "SORT");
        public final static Property MealId = new Property(4, int.class, "mealId", false, "MEAL_ID");
    }


    public CategoryTableDao(DaoConfig config) {
        super(config);
    }
    
    public CategoryTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CATEGORY_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CATEGORY_ID\" TEXT," + // 1: categoryId
                "\"CATEGORY_NAME\" TEXT," + // 2: categoryName
                "\"SORT\" TEXT," + // 3: sort
                "\"MEAL_ID\" INTEGER NOT NULL );"); // 4: mealId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CATEGORY_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CategoryTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String categoryId = entity.getCategoryId();
        if (categoryId != null) {
            stmt.bindString(2, categoryId);
        }
 
        String categoryName = entity.getCategoryName();
        if (categoryName != null) {
            stmt.bindString(3, categoryName);
        }
 
        String sort = entity.getSort();
        if (sort != null) {
            stmt.bindString(4, sort);
        }
        stmt.bindLong(5, entity.getMealId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CategoryTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String categoryId = entity.getCategoryId();
        if (categoryId != null) {
            stmt.bindString(2, categoryId);
        }
 
        String categoryName = entity.getCategoryName();
        if (categoryName != null) {
            stmt.bindString(3, categoryName);
        }
 
        String sort = entity.getSort();
        if (sort != null) {
            stmt.bindString(4, sort);
        }
        stmt.bindLong(5, entity.getMealId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CategoryTable readEntity(Cursor cursor, int offset) {
        CategoryTable entity = new CategoryTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // categoryId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // categoryName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // sort
            cursor.getInt(offset + 4) // mealId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CategoryTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCategoryId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCategoryName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSort(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMealId(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CategoryTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CategoryTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CategoryTable entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
