package com.yannuo.dgcanteen.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yannuo.dgcanteen.greendao.entity.CategoryTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CATEGORY_TABLE".
*/
public class CategoryTableDao extends AbstractDao<CategoryTable, String> {

    public static final String TABLENAME = "CATEGORY_TABLE";

    /**
     * Properties of entity CategoryTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CategoryId = new Property(0, String.class, "categoryId", true, "CATEGORY_ID");
        public final static Property CategoryName = new Property(1, String.class, "categoryName", false, "CATEGORY_NAME");
        public final static Property Sort = new Property(2, String.class, "sort", false, "SORT");
        public final static Property MealId = new Property(3, int.class, "mealId", false, "MEAL_ID");
    }


    public CategoryTableDao(DaoConfig config) {
        super(config);
    }
    
    public CategoryTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CATEGORY_TABLE\" (" + //
                "\"CATEGORY_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: categoryId
                "\"CATEGORY_NAME\" TEXT," + // 1: categoryName
                "\"SORT\" TEXT," + // 2: sort
                "\"MEAL_ID\" INTEGER NOT NULL );"); // 3: mealId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CATEGORY_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CategoryTable entity) {
        stmt.clearBindings();
 
        String categoryId = entity.getCategoryId();
        if (categoryId != null) {
            stmt.bindString(1, categoryId);
        }
 
        String categoryName = entity.getCategoryName();
        if (categoryName != null) {
            stmt.bindString(2, categoryName);
        }
 
        String sort = entity.getSort();
        if (sort != null) {
            stmt.bindString(3, sort);
        }
        stmt.bindLong(4, entity.getMealId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CategoryTable entity) {
        stmt.clearBindings();
 
        String categoryId = entity.getCategoryId();
        if (categoryId != null) {
            stmt.bindString(1, categoryId);
        }
 
        String categoryName = entity.getCategoryName();
        if (categoryName != null) {
            stmt.bindString(2, categoryName);
        }
 
        String sort = entity.getSort();
        if (sort != null) {
            stmt.bindString(3, sort);
        }
        stmt.bindLong(4, entity.getMealId());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public CategoryTable readEntity(Cursor cursor, int offset) {
        CategoryTable entity = new CategoryTable( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // categoryId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // categoryName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sort
            cursor.getInt(offset + 3) // mealId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CategoryTable entity, int offset) {
        entity.setCategoryId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setCategoryName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSort(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMealId(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final String updateKeyAfterInsert(CategoryTable entity, long rowId) {
        return entity.getCategoryId();
    }
    
    @Override
    public String getKey(CategoryTable entity) {
        if(entity != null) {
            return entity.getCategoryId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CategoryTable entity) {
        return entity.getCategoryId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
