package com.yannuo.dgcanteen.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yannuo.dgcanteen.greendao.entity.AccListTable;
import com.yannuo.dgcanteen.greendao.entity.CategoryTable;
import com.yannuo.dgcanteen.greendao.entity.DishesTable;
import com.yannuo.dgcanteen.greendao.entity.FaceRecord;
import com.yannuo.dgcanteen.greendao.entity.FaceTokens;
import com.yannuo.dgcanteen.greendao.entity.MealTable;
import com.yannuo.dgcanteen.greendao.entity.OfflineAccListTable;
import com.yannuo.dgcanteen.greendao.entity.OfflineDishTable;
import com.yannuo.dgcanteen.greendao.entity.OfflineOrderTable;
import com.yannuo.dgcanteen.greendao.entity.PayDishTable;
import com.yannuo.dgcanteen.greendao.entity.PayOrderTable;
import com.yannuo.dgcanteen.greendao.entity.Persons;
import com.yannuo.dgcanteen.greendao.entity.QuotaTimeTable;
import com.yannuo.dgcanteen.greendao.entity.SwPayOrderTable;
import com.yannuo.dgcanteen.greendao.entity.VerifyDishes;

import com.yannuo.dgcanteen.greendao.dao.AccListTableDao;
import com.yannuo.dgcanteen.greendao.dao.CategoryTableDao;
import com.yannuo.dgcanteen.greendao.dao.DishesTableDao;
import com.yannuo.dgcanteen.greendao.dao.FaceRecordDao;
import com.yannuo.dgcanteen.greendao.dao.FaceTokensDao;
import com.yannuo.dgcanteen.greendao.dao.MealTableDao;
import com.yannuo.dgcanteen.greendao.dao.OfflineAccListTableDao;
import com.yannuo.dgcanteen.greendao.dao.OfflineDishTableDao;
import com.yannuo.dgcanteen.greendao.dao.OfflineOrderTableDao;
import com.yannuo.dgcanteen.greendao.dao.PayDishTableDao;
import com.yannuo.dgcanteen.greendao.dao.PayOrderTableDao;
import com.yannuo.dgcanteen.greendao.dao.PersonsDao;
import com.yannuo.dgcanteen.greendao.dao.QuotaTimeTableDao;
import com.yannuo.dgcanteen.greendao.dao.SwPayOrderTableDao;
import com.yannuo.dgcanteen.greendao.dao.VerifyDishesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accListTableDaoConfig;
    private final DaoConfig categoryTableDaoConfig;
    private final DaoConfig dishesTableDaoConfig;
    private final DaoConfig faceRecordDaoConfig;
    private final DaoConfig faceTokensDaoConfig;
    private final DaoConfig mealTableDaoConfig;
    private final DaoConfig offlineAccListTableDaoConfig;
    private final DaoConfig offlineDishTableDaoConfig;
    private final DaoConfig offlineOrderTableDaoConfig;
    private final DaoConfig payDishTableDaoConfig;
    private final DaoConfig payOrderTableDaoConfig;
    private final DaoConfig personsDaoConfig;
    private final DaoConfig quotaTimeTableDaoConfig;
    private final DaoConfig swPayOrderTableDaoConfig;
    private final DaoConfig verifyDishesDaoConfig;

    private final AccListTableDao accListTableDao;
    private final CategoryTableDao categoryTableDao;
    private final DishesTableDao dishesTableDao;
    private final FaceRecordDao faceRecordDao;
    private final FaceTokensDao faceTokensDao;
    private final MealTableDao mealTableDao;
    private final OfflineAccListTableDao offlineAccListTableDao;
    private final OfflineDishTableDao offlineDishTableDao;
    private final OfflineOrderTableDao offlineOrderTableDao;
    private final PayDishTableDao payDishTableDao;
    private final PayOrderTableDao payOrderTableDao;
    private final PersonsDao personsDao;
    private final QuotaTimeTableDao quotaTimeTableDao;
    private final SwPayOrderTableDao swPayOrderTableDao;
    private final VerifyDishesDao verifyDishesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accListTableDaoConfig = daoConfigMap.get(AccListTableDao.class).clone();
        accListTableDaoConfig.initIdentityScope(type);

        categoryTableDaoConfig = daoConfigMap.get(CategoryTableDao.class).clone();
        categoryTableDaoConfig.initIdentityScope(type);

        dishesTableDaoConfig = daoConfigMap.get(DishesTableDao.class).clone();
        dishesTableDaoConfig.initIdentityScope(type);

        faceRecordDaoConfig = daoConfigMap.get(FaceRecordDao.class).clone();
        faceRecordDaoConfig.initIdentityScope(type);

        faceTokensDaoConfig = daoConfigMap.get(FaceTokensDao.class).clone();
        faceTokensDaoConfig.initIdentityScope(type);

        mealTableDaoConfig = daoConfigMap.get(MealTableDao.class).clone();
        mealTableDaoConfig.initIdentityScope(type);

        offlineAccListTableDaoConfig = daoConfigMap.get(OfflineAccListTableDao.class).clone();
        offlineAccListTableDaoConfig.initIdentityScope(type);

        offlineDishTableDaoConfig = daoConfigMap.get(OfflineDishTableDao.class).clone();
        offlineDishTableDaoConfig.initIdentityScope(type);

        offlineOrderTableDaoConfig = daoConfigMap.get(OfflineOrderTableDao.class).clone();
        offlineOrderTableDaoConfig.initIdentityScope(type);

        payDishTableDaoConfig = daoConfigMap.get(PayDishTableDao.class).clone();
        payDishTableDaoConfig.initIdentityScope(type);

        payOrderTableDaoConfig = daoConfigMap.get(PayOrderTableDao.class).clone();
        payOrderTableDaoConfig.initIdentityScope(type);

        personsDaoConfig = daoConfigMap.get(PersonsDao.class).clone();
        personsDaoConfig.initIdentityScope(type);

        quotaTimeTableDaoConfig = daoConfigMap.get(QuotaTimeTableDao.class).clone();
        quotaTimeTableDaoConfig.initIdentityScope(type);

        swPayOrderTableDaoConfig = daoConfigMap.get(SwPayOrderTableDao.class).clone();
        swPayOrderTableDaoConfig.initIdentityScope(type);

        verifyDishesDaoConfig = daoConfigMap.get(VerifyDishesDao.class).clone();
        verifyDishesDaoConfig.initIdentityScope(type);

        accListTableDao = new AccListTableDao(accListTableDaoConfig, this);
        categoryTableDao = new CategoryTableDao(categoryTableDaoConfig, this);
        dishesTableDao = new DishesTableDao(dishesTableDaoConfig, this);
        faceRecordDao = new FaceRecordDao(faceRecordDaoConfig, this);
        faceTokensDao = new FaceTokensDao(faceTokensDaoConfig, this);
        mealTableDao = new MealTableDao(mealTableDaoConfig, this);
        offlineAccListTableDao = new OfflineAccListTableDao(offlineAccListTableDaoConfig, this);
        offlineDishTableDao = new OfflineDishTableDao(offlineDishTableDaoConfig, this);
        offlineOrderTableDao = new OfflineOrderTableDao(offlineOrderTableDaoConfig, this);
        payDishTableDao = new PayDishTableDao(payDishTableDaoConfig, this);
        payOrderTableDao = new PayOrderTableDao(payOrderTableDaoConfig, this);
        personsDao = new PersonsDao(personsDaoConfig, this);
        quotaTimeTableDao = new QuotaTimeTableDao(quotaTimeTableDaoConfig, this);
        swPayOrderTableDao = new SwPayOrderTableDao(swPayOrderTableDaoConfig, this);
        verifyDishesDao = new VerifyDishesDao(verifyDishesDaoConfig, this);

        registerDao(AccListTable.class, accListTableDao);
        registerDao(CategoryTable.class, categoryTableDao);
        registerDao(DishesTable.class, dishesTableDao);
        registerDao(FaceRecord.class, faceRecordDao);
        registerDao(FaceTokens.class, faceTokensDao);
        registerDao(MealTable.class, mealTableDao);
        registerDao(OfflineAccListTable.class, offlineAccListTableDao);
        registerDao(OfflineDishTable.class, offlineDishTableDao);
        registerDao(OfflineOrderTable.class, offlineOrderTableDao);
        registerDao(PayDishTable.class, payDishTableDao);
        registerDao(PayOrderTable.class, payOrderTableDao);
        registerDao(Persons.class, personsDao);
        registerDao(QuotaTimeTable.class, quotaTimeTableDao);
        registerDao(SwPayOrderTable.class, swPayOrderTableDao);
        registerDao(VerifyDishes.class, verifyDishesDao);
    }
    
    public void clear() {
        accListTableDaoConfig.clearIdentityScope();
        categoryTableDaoConfig.clearIdentityScope();
        dishesTableDaoConfig.clearIdentityScope();
        faceRecordDaoConfig.clearIdentityScope();
        faceTokensDaoConfig.clearIdentityScope();
        mealTableDaoConfig.clearIdentityScope();
        offlineAccListTableDaoConfig.clearIdentityScope();
        offlineDishTableDaoConfig.clearIdentityScope();
        offlineOrderTableDaoConfig.clearIdentityScope();
        payDishTableDaoConfig.clearIdentityScope();
        payOrderTableDaoConfig.clearIdentityScope();
        personsDaoConfig.clearIdentityScope();
        quotaTimeTableDaoConfig.clearIdentityScope();
        swPayOrderTableDaoConfig.clearIdentityScope();
        verifyDishesDaoConfig.clearIdentityScope();
    }

    public AccListTableDao getAccListTableDao() {
        return accListTableDao;
    }

    public CategoryTableDao getCategoryTableDao() {
        return categoryTableDao;
    }

    public DishesTableDao getDishesTableDao() {
        return dishesTableDao;
    }

    public FaceRecordDao getFaceRecordDao() {
        return faceRecordDao;
    }

    public FaceTokensDao getFaceTokensDao() {
        return faceTokensDao;
    }

    public MealTableDao getMealTableDao() {
        return mealTableDao;
    }

    public OfflineAccListTableDao getOfflineAccListTableDao() {
        return offlineAccListTableDao;
    }

    public OfflineDishTableDao getOfflineDishTableDao() {
        return offlineDishTableDao;
    }

    public OfflineOrderTableDao getOfflineOrderTableDao() {
        return offlineOrderTableDao;
    }

    public PayDishTableDao getPayDishTableDao() {
        return payDishTableDao;
    }

    public PayOrderTableDao getPayOrderTableDao() {
        return payOrderTableDao;
    }

    public PersonsDao getPersonsDao() {
        return personsDao;
    }

    public QuotaTimeTableDao getQuotaTimeTableDao() {
        return quotaTimeTableDao;
    }

    public SwPayOrderTableDao getSwPayOrderTableDao() {
        return swPayOrderTableDao;
    }

    public VerifyDishesDao getVerifyDishesDao() {
        return verifyDishesDao;
    }

}
