package com.yannuo.dgcanteen.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yannuo.dgcanteen.greendao.entity.DishesTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DISHES_TABLE".
*/
public class DishesTableDao extends AbstractDao<DishesTable, String> {

    public static final String TABLENAME = "DISHES_TABLE";

    /**
     * Properties of entity DishesTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property DishesId = new Property(0, String.class, "dishesId", true, "DISHES_ID");
        public final static Property DishesName = new Property(1, String.class, "dishesName", false, "DISHES_NAME");
        public final static Property MealId = new Property(2, int.class, "mealId", false, "MEAL_ID");
        public final static Property Price = new Property(3, Double.class, "price", false, "PRICE");
        public final static Property Unit = new Property(4, String.class, "unit", false, "UNIT");
        public final static Property ImgUrl = new Property(5, String.class, "imgUrl", false, "IMG_URL");
        public final static Property Status = new Property(6, int.class, "status", false, "STATUS");
        public final static Property CategoryName = new Property(7, String.class, "categoryName", false, "CATEGORY_NAME");
    }


    public DishesTableDao(DaoConfig config) {
        super(config);
    }
    
    public DishesTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DISHES_TABLE\" (" + //
                "\"DISHES_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: dishesId
                "\"DISHES_NAME\" TEXT NOT NULL ," + // 1: dishesName
                "\"MEAL_ID\" INTEGER NOT NULL ," + // 2: mealId
                "\"PRICE\" REAL NOT NULL ," + // 3: price
                "\"UNIT\" TEXT," + // 4: unit
                "\"IMG_URL\" TEXT," + // 5: imgUrl
                "\"STATUS\" INTEGER NOT NULL ," + // 6: status
                "\"CATEGORY_NAME\" TEXT);"); // 7: categoryName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DISHES_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DishesTable entity) {
        stmt.clearBindings();
 
        String dishesId = entity.getDishesId();
        if (dishesId != null) {
            stmt.bindString(1, dishesId);
        }
        stmt.bindString(2, entity.getDishesName());
        stmt.bindLong(3, entity.getMealId());
        stmt.bindDouble(4, entity.getPrice());
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(5, unit);
        }
 
        String imgUrl = entity.getImgUrl();
        if (imgUrl != null) {
            stmt.bindString(6, imgUrl);
        }
        stmt.bindLong(7, entity.getStatus());
 
        String categoryName = entity.getCategoryName();
        if (categoryName != null) {
            stmt.bindString(8, categoryName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DishesTable entity) {
        stmt.clearBindings();
 
        String dishesId = entity.getDishesId();
        if (dishesId != null) {
            stmt.bindString(1, dishesId);
        }
        stmt.bindString(2, entity.getDishesName());
        stmt.bindLong(3, entity.getMealId());
        stmt.bindDouble(4, entity.getPrice());
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(5, unit);
        }
 
        String imgUrl = entity.getImgUrl();
        if (imgUrl != null) {
            stmt.bindString(6, imgUrl);
        }
        stmt.bindLong(7, entity.getStatus());
 
        String categoryName = entity.getCategoryName();
        if (categoryName != null) {
            stmt.bindString(8, categoryName);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public DishesTable readEntity(Cursor cursor, int offset) {
        DishesTable entity = new DishesTable( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // dishesId
            cursor.getString(offset + 1), // dishesName
            cursor.getInt(offset + 2), // mealId
            cursor.getDouble(offset + 3), // price
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // unit
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // imgUrl
            cursor.getInt(offset + 6), // status
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // categoryName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DishesTable entity, int offset) {
        entity.setDishesId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setDishesName(cursor.getString(offset + 1));
        entity.setMealId(cursor.getInt(offset + 2));
        entity.setPrice(cursor.getDouble(offset + 3));
        entity.setUnit(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setImgUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setStatus(cursor.getInt(offset + 6));
        entity.setCategoryName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final String updateKeyAfterInsert(DishesTable entity, long rowId) {
        return entity.getDishesId();
    }
    
    @Override
    public String getKey(DishesTable entity) {
        if(entity != null) {
            return entity.getDishesId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DishesTable entity) {
        return entity.getDishesId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
