package com.yannuo.dgcanteen.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yannuo.dgcanteen.greendao.entity.FacePayTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FACE_PAY_TABLE".
*/
public class FacePayTableDao extends AbstractDao<FacePayTable, Long> {

    public static final String TABLENAME = "FACE_PAY_TABLE";

    /**
     * Properties of entity FacePayTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DeviceId = new Property(1, String.class, "deviceId", false, "DEVICE_ID");
        public final static Property CampusId = new Property(2, String.class, "campusId", false, "CAMPUS_ID");
        public final static Property BusinessId = new Property(3, String.class, "businessId", false, "BUSINESS_ID");
        public final static Property BusinessName = new Property(4, String.class, "businessName", false, "BUSINESS_NAME");
        public final static Property VposId = new Property(5, String.class, "vposId", false, "VPOS_ID");
        public final static Property Payment = new Property(6, String.class, "payment", false, "PAYMENT");
        public final static Property ActualPayment = new Property(7, String.class, "actualPayment", false, "ACTUAL_PAYMENT");
        public final static Property Offline = new Property(8, String.class, "offline", false, "OFFLINE");
        public final static Property SignTime = new Property(9, String.class, "signTime", false, "SIGN_TIME");
        public final static Property PersonNumber = new Property(10, String.class, "personNumber", false, "PERSON_NUMBER");
        public final static Property CustId = new Property(11, String.class, "custId", false, "CUST_ID");
        public final static Property OrderId = new Property(12, String.class, "orderId", false, "ORDER_ID");
        public final static Property FaceBase64 = new Property(13, String.class, "faceBase64", false, "FACE_BASE64");
        public final static Property FaceScore = new Property(14, String.class, "faceScore", false, "FACE_SCORE");
    }


    public FacePayTableDao(DaoConfig config) {
        super(config);
    }
    
    public FacePayTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FACE_PAY_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DEVICE_ID\" TEXT," + // 1: deviceId
                "\"CAMPUS_ID\" TEXT," + // 2: campusId
                "\"BUSINESS_ID\" TEXT," + // 3: businessId
                "\"BUSINESS_NAME\" TEXT," + // 4: businessName
                "\"VPOS_ID\" TEXT," + // 5: vposId
                "\"PAYMENT\" TEXT," + // 6: payment
                "\"ACTUAL_PAYMENT\" TEXT," + // 7: actualPayment
                "\"OFFLINE\" TEXT," + // 8: offline
                "\"SIGN_TIME\" TEXT," + // 9: signTime
                "\"PERSON_NUMBER\" TEXT," + // 10: personNumber
                "\"CUST_ID\" TEXT," + // 11: custId
                "\"ORDER_ID\" TEXT," + // 12: orderId
                "\"FACE_BASE64\" TEXT," + // 13: faceBase64
                "\"FACE_SCORE\" TEXT);"); // 14: faceScore
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FACE_PAY_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FacePayTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindString(2, deviceId);
        }
 
        String campusId = entity.getCampusId();
        if (campusId != null) {
            stmt.bindString(3, campusId);
        }
 
        String businessId = entity.getBusinessId();
        if (businessId != null) {
            stmt.bindString(4, businessId);
        }
 
        String businessName = entity.getBusinessName();
        if (businessName != null) {
            stmt.bindString(5, businessName);
        }
 
        String vposId = entity.getVposId();
        if (vposId != null) {
            stmt.bindString(6, vposId);
        }
 
        String payment = entity.getPayment();
        if (payment != null) {
            stmt.bindString(7, payment);
        }
 
        String actualPayment = entity.getActualPayment();
        if (actualPayment != null) {
            stmt.bindString(8, actualPayment);
        }
 
        String offline = entity.getOffline();
        if (offline != null) {
            stmt.bindString(9, offline);
        }
 
        String signTime = entity.getSignTime();
        if (signTime != null) {
            stmt.bindString(10, signTime);
        }
 
        String personNumber = entity.getPersonNumber();
        if (personNumber != null) {
            stmt.bindString(11, personNumber);
        }
 
        String custId = entity.getCustId();
        if (custId != null) {
            stmt.bindString(12, custId);
        }
 
        String orderId = entity.getOrderId();
        if (orderId != null) {
            stmt.bindString(13, orderId);
        }
 
        String faceBase64 = entity.getFaceBase64();
        if (faceBase64 != null) {
            stmt.bindString(14, faceBase64);
        }
 
        String faceScore = entity.getFaceScore();
        if (faceScore != null) {
            stmt.bindString(15, faceScore);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FacePayTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindString(2, deviceId);
        }
 
        String campusId = entity.getCampusId();
        if (campusId != null) {
            stmt.bindString(3, campusId);
        }
 
        String businessId = entity.getBusinessId();
        if (businessId != null) {
            stmt.bindString(4, businessId);
        }
 
        String businessName = entity.getBusinessName();
        if (businessName != null) {
            stmt.bindString(5, businessName);
        }
 
        String vposId = entity.getVposId();
        if (vposId != null) {
            stmt.bindString(6, vposId);
        }
 
        String payment = entity.getPayment();
        if (payment != null) {
            stmt.bindString(7, payment);
        }
 
        String actualPayment = entity.getActualPayment();
        if (actualPayment != null) {
            stmt.bindString(8, actualPayment);
        }
 
        String offline = entity.getOffline();
        if (offline != null) {
            stmt.bindString(9, offline);
        }
 
        String signTime = entity.getSignTime();
        if (signTime != null) {
            stmt.bindString(10, signTime);
        }
 
        String personNumber = entity.getPersonNumber();
        if (personNumber != null) {
            stmt.bindString(11, personNumber);
        }
 
        String custId = entity.getCustId();
        if (custId != null) {
            stmt.bindString(12, custId);
        }
 
        String orderId = entity.getOrderId();
        if (orderId != null) {
            stmt.bindString(13, orderId);
        }
 
        String faceBase64 = entity.getFaceBase64();
        if (faceBase64 != null) {
            stmt.bindString(14, faceBase64);
        }
 
        String faceScore = entity.getFaceScore();
        if (faceScore != null) {
            stmt.bindString(15, faceScore);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FacePayTable readEntity(Cursor cursor, int offset) {
        FacePayTable entity = new FacePayTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // deviceId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // campusId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // businessId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // businessName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // vposId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // payment
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // actualPayment
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // offline
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // signTime
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // personNumber
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // custId
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // orderId
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // faceBase64
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14) // faceScore
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FacePayTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDeviceId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCampusId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBusinessId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBusinessName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setVposId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPayment(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setActualPayment(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setOffline(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSignTime(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setPersonNumber(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setCustId(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setOrderId(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setFaceBase64(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setFaceScore(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FacePayTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FacePayTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FacePayTable entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
