package com.yannuo.dgcanteen.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yannuo.dgcanteen.greendao.entity.FaceRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FACE_RECORD".
*/
public class FaceRecordDao extends AbstractDao<FaceRecord, Long> {

    public static final String TABLENAME = "FACE_RECORD";

    /**
     * Properties of entity FaceRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CustId = new Property(1, String.class, "custId", false, "CUST_ID");
        public final static Property Image = new Property(2, String.class, "image", false, "IMAGE");
        public final static Property Tryd = new Property(3, Boolean.class, "tryd", false, "TRYD");
    }


    public FaceRecordDao(DaoConfig config) {
        super(config);
    }
    
    public FaceRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FACE_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CUST_ID\" TEXT UNIQUE ," + // 1: custId
                "\"IMAGE\" TEXT NOT NULL ," + // 2: image
                "\"TRYD\" INTEGER);"); // 3: tryd
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FACE_RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FaceRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String custId = entity.getCustId();
        if (custId != null) {
            stmt.bindString(2, custId);
        }
        stmt.bindString(3, entity.getImage());
 
        Boolean tryd = entity.getTryd();
        if (tryd != null) {
            stmt.bindLong(4, tryd ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FaceRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String custId = entity.getCustId();
        if (custId != null) {
            stmt.bindString(2, custId);
        }
        stmt.bindString(3, entity.getImage());
 
        Boolean tryd = entity.getTryd();
        if (tryd != null) {
            stmt.bindLong(4, tryd ? 1L: 0L);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FaceRecord readEntity(Cursor cursor, int offset) {
        FaceRecord entity = new FaceRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // custId
            cursor.getString(offset + 2), // image
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // tryd
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FaceRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCustId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImage(cursor.getString(offset + 2));
        entity.setTryd(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FaceRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FaceRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FaceRecord entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
