package com.yannuo.dgcanteen.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yannuo.dgcanteen.greendao.entity.MealTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEAL_TABLE".
*/
public class MealTableDao extends AbstractDao<MealTable, Long> {

    public static final String TABLENAME = "MEAL_TABLE";

    /**
     * Properties of entity MealTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MealId = new Property(1, int.class, "mealId", false, "MEAL_ID");
        public final static Property MealName = new Property(2, String.class, "mealName", false, "MEAL_NAME");
        public final static Property StartTime = new Property(3, java.util.Date.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(4, java.util.Date.class, "endTime", false, "END_TIME");
    }


    public MealTableDao(DaoConfig config) {
        super(config);
    }
    
    public MealTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEAL_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MEAL_ID\" INTEGER NOT NULL UNIQUE ," + // 1: mealId
                "\"MEAL_NAME\" TEXT NOT NULL ," + // 2: mealName
                "\"START_TIME\" INTEGER NOT NULL ," + // 3: startTime
                "\"END_TIME\" INTEGER);"); // 4: endTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEAL_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MealTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMealId());
        stmt.bindString(3, entity.getMealName());
        stmt.bindLong(4, entity.getStartTime().getTime());
 
        java.util.Date endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(5, endTime.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MealTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMealId());
        stmt.bindString(3, entity.getMealName());
        stmt.bindLong(4, entity.getStartTime().getTime());
 
        java.util.Date endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(5, endTime.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MealTable readEntity(Cursor cursor, int offset) {
        MealTable entity = new MealTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // mealId
            cursor.getString(offset + 2), // mealName
            new java.util.Date(cursor.getLong(offset + 3)), // startTime
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)) // endTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MealTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMealId(cursor.getInt(offset + 1));
        entity.setMealName(cursor.getString(offset + 2));
        entity.setStartTime(new java.util.Date(cursor.getLong(offset + 3)));
        entity.setEndTime(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MealTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MealTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MealTable entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
