package com.yannuo.dgcanteen.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yannuo.dgcanteen.greendao.entity.MealTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEAL_TABLE".
*/
public class MealTableDao extends AbstractDao<MealTable, String> {

    public static final String TABLENAME = "MEAL_TABLE";

    /**
     * Properties of entity MealTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property MealId = new Property(0, String.class, "mealId", true, "MEAL_ID");
        public final static Property MealName = new Property(1, String.class, "mealName", false, "MEAL_NAME");
        public final static Property StartTime = new Property(2, java.util.Date.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(3, java.util.Date.class, "endTime", false, "END_TIME");
    }


    public MealTableDao(DaoConfig config) {
        super(config);
    }
    
    public MealTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEAL_TABLE\" (" + //
                "\"MEAL_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: mealId
                "\"MEAL_NAME\" TEXT NOT NULL ," + // 1: mealName
                "\"START_TIME\" INTEGER NOT NULL ," + // 2: startTime
                "\"END_TIME\" INTEGER);"); // 3: endTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEAL_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MealTable entity) {
        stmt.clearBindings();
 
        String mealId = entity.getMealId();
        if (mealId != null) {
            stmt.bindString(1, mealId);
        }
        stmt.bindString(2, entity.getMealName());
        stmt.bindLong(3, entity.getStartTime().getTime());
 
        java.util.Date endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(4, endTime.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MealTable entity) {
        stmt.clearBindings();
 
        String mealId = entity.getMealId();
        if (mealId != null) {
            stmt.bindString(1, mealId);
        }
        stmt.bindString(2, entity.getMealName());
        stmt.bindLong(3, entity.getStartTime().getTime());
 
        java.util.Date endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(4, endTime.getTime());
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public MealTable readEntity(Cursor cursor, int offset) {
        MealTable entity = new MealTable( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // mealId
            cursor.getString(offset + 1), // mealName
            new java.util.Date(cursor.getLong(offset + 2)), // startTime
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)) // endTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MealTable entity, int offset) {
        entity.setMealId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setMealName(cursor.getString(offset + 1));
        entity.setStartTime(new java.util.Date(cursor.getLong(offset + 2)));
        entity.setEndTime(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
     }
    
    @Override
    protected final String updateKeyAfterInsert(MealTable entity, long rowId) {
        return entity.getMealId();
    }
    
    @Override
    public String getKey(MealTable entity) {
        if(entity != null) {
            return entity.getMealId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MealTable entity) {
        return entity.getMealId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
