package com.yannuo.dgcanteen.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yannuo.dgcanteen.greendao.entity.OfflineOrderTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "OFFLINE_ORDER_TABLE".
*/
public class OfflineOrderTableDao extends AbstractDao<OfflineOrderTable, Long> {

    public static final String TABLENAME = "OFFLINE_ORDER_TABLE";

    /**
     * Properties of entity OfflineOrderTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BusinessId = new Property(1, String.class, "businessId", false, "BUSINESS_ID");
        public final static Property BusinessName = new Property(2, String.class, "businessName", false, "BUSINESS_NAME");
        public final static Property CampusId = new Property(3, String.class, "campusId", false, "CAMPUS_ID");
        public final static Property CorpId = new Property(4, String.class, "corpId", false, "CORP_ID");
        public final static Property VposId = new Property(5, String.class, "vposId", false, "VPOS_ID");
        public final static Property DeviceId = new Property(6, String.class, "deviceId", false, "DEVICE_ID");
        public final static Property CustId = new Property(7, String.class, "custId", false, "CUST_ID");
        public final static Property Username = new Property(8, String.class, "username", false, "USERNAME");
        public final static Property PayType = new Property(9, String.class, "payType", false, "PAY_TYPE");
        public final static Property PayContent = new Property(10, String.class, "payContent", false, "PAY_CONTENT");
        public final static Property Payment = new Property(11, String.class, "payment", false, "PAYMENT");
        public final static Property ActualPayment = new Property(12, String.class, "actualPayment", false, "ACTUAL_PAYMENT");
        public final static Property SessionId = new Property(13, String.class, "sessionId", false, "SESSION_ID");
        public final static Property SignTime = new Property(14, String.class, "signTime", false, "SIGN_TIME");
        public final static Property Offline = new Property(15, String.class, "offline", false, "OFFLINE");
        public final static Property Flag = new Property(16, Integer.class, "flag", false, "FLAG");
    }

    private DaoSession daoSession;


    public OfflineOrderTableDao(DaoConfig config) {
        super(config);
    }
    
    public OfflineOrderTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"OFFLINE_ORDER_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"BUSINESS_ID\" TEXT," + // 1: businessId
                "\"BUSINESS_NAME\" TEXT," + // 2: businessName
                "\"CAMPUS_ID\" TEXT," + // 3: campusId
                "\"CORP_ID\" TEXT," + // 4: corpId
                "\"VPOS_ID\" TEXT," + // 5: vposId
                "\"DEVICE_ID\" TEXT," + // 6: deviceId
                "\"CUST_ID\" TEXT," + // 7: custId
                "\"USERNAME\" TEXT," + // 8: username
                "\"PAY_TYPE\" TEXT," + // 9: payType
                "\"PAY_CONTENT\" TEXT," + // 10: payContent
                "\"PAYMENT\" TEXT," + // 11: payment
                "\"ACTUAL_PAYMENT\" TEXT," + // 12: actualPayment
                "\"SESSION_ID\" TEXT UNIQUE ," + // 13: sessionId
                "\"SIGN_TIME\" TEXT," + // 14: signTime
                "\"OFFLINE\" TEXT," + // 15: offline
                "\"FLAG\" INTEGER);"); // 16: flag
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"OFFLINE_ORDER_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OfflineOrderTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String businessId = entity.getBusinessId();
        if (businessId != null) {
            stmt.bindString(2, businessId);
        }
 
        String businessName = entity.getBusinessName();
        if (businessName != null) {
            stmt.bindString(3, businessName);
        }
 
        String campusId = entity.getCampusId();
        if (campusId != null) {
            stmt.bindString(4, campusId);
        }
 
        String corpId = entity.getCorpId();
        if (corpId != null) {
            stmt.bindString(5, corpId);
        }
 
        String vposId = entity.getVposId();
        if (vposId != null) {
            stmt.bindString(6, vposId);
        }
 
        String deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindString(7, deviceId);
        }
 
        String custId = entity.getCustId();
        if (custId != null) {
            stmt.bindString(8, custId);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(9, username);
        }
 
        String payType = entity.getPayType();
        if (payType != null) {
            stmt.bindString(10, payType);
        }
 
        String payContent = entity.getPayContent();
        if (payContent != null) {
            stmt.bindString(11, payContent);
        }
 
        String payment = entity.getPayment();
        if (payment != null) {
            stmt.bindString(12, payment);
        }
 
        String actualPayment = entity.getActualPayment();
        if (actualPayment != null) {
            stmt.bindString(13, actualPayment);
        }
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(14, sessionId);
        }
 
        String signTime = entity.getSignTime();
        if (signTime != null) {
            stmt.bindString(15, signTime);
        }
 
        String offline = entity.getOffline();
        if (offline != null) {
            stmt.bindString(16, offline);
        }
 
        Integer flag = entity.getFlag();
        if (flag != null) {
            stmt.bindLong(17, flag);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OfflineOrderTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String businessId = entity.getBusinessId();
        if (businessId != null) {
            stmt.bindString(2, businessId);
        }
 
        String businessName = entity.getBusinessName();
        if (businessName != null) {
            stmt.bindString(3, businessName);
        }
 
        String campusId = entity.getCampusId();
        if (campusId != null) {
            stmt.bindString(4, campusId);
        }
 
        String corpId = entity.getCorpId();
        if (corpId != null) {
            stmt.bindString(5, corpId);
        }
 
        String vposId = entity.getVposId();
        if (vposId != null) {
            stmt.bindString(6, vposId);
        }
 
        String deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindString(7, deviceId);
        }
 
        String custId = entity.getCustId();
        if (custId != null) {
            stmt.bindString(8, custId);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(9, username);
        }
 
        String payType = entity.getPayType();
        if (payType != null) {
            stmt.bindString(10, payType);
        }
 
        String payContent = entity.getPayContent();
        if (payContent != null) {
            stmt.bindString(11, payContent);
        }
 
        String payment = entity.getPayment();
        if (payment != null) {
            stmt.bindString(12, payment);
        }
 
        String actualPayment = entity.getActualPayment();
        if (actualPayment != null) {
            stmt.bindString(13, actualPayment);
        }
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(14, sessionId);
        }
 
        String signTime = entity.getSignTime();
        if (signTime != null) {
            stmt.bindString(15, signTime);
        }
 
        String offline = entity.getOffline();
        if (offline != null) {
            stmt.bindString(16, offline);
        }
 
        Integer flag = entity.getFlag();
        if (flag != null) {
            stmt.bindLong(17, flag);
        }
    }

    @Override
    protected final void attachEntity(OfflineOrderTable entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OfflineOrderTable readEntity(Cursor cursor, int offset) {
        OfflineOrderTable entity = new OfflineOrderTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // businessId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // businessName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // campusId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // corpId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // vposId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // deviceId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // custId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // username
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // payType
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // payContent
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // payment
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // actualPayment
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // sessionId
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // signTime
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // offline
            cursor.isNull(offset + 16) ? null : cursor.getInt(offset + 16) // flag
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OfflineOrderTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBusinessId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBusinessName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCampusId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCorpId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setVposId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDeviceId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCustId(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setUsername(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setPayType(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setPayContent(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setPayment(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setActualPayment(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setSessionId(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setSignTime(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setOffline(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setFlag(cursor.isNull(offset + 16) ? null : cursor.getInt(offset + 16));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OfflineOrderTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OfflineOrderTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OfflineOrderTable entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
