package com.yannuo.dgcanteen.greendao.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.yannuo.dgcanteen.greendao.entity.OfflineOrderTable;

import com.yannuo.dgcanteen.greendao.entity.OfflineAccListTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "OFFLINE_ACC_LIST_TABLE".
*/
public class OfflineAccListTableDao extends AbstractDao<OfflineAccListTable, Long> {

    public static final String TABLENAME = "OFFLINE_ACC_LIST_TABLE";

    /**
     * Properties of entity OfflineAccListTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AccId = new Property(1, Long.class, "accId", false, "ACC_ID");
        public final static Property ACC_BAL = new Property(2, String.class, "ACC_BAL", false, "ACC__BAL");
        public final static Property ACC_NO = new Property(3, String.class, "ACC_NO", false, "ACC__NO");
        public final static Property ACC_TYPE = new Property(4, String.class, "ACC_TYPE", false, "ACC__TYPE");
        public final static Property PAYMENT = new Property(5, String.class, "PAYMENT", false, "PAYMENT");
        public final static Property TRAN_ID = new Property(6, String.class, "TRAN_ID", false, "TRAN__ID");
    }

    private DaoSession daoSession;

    private Query<OfflineAccListTable> offlineOrderTable_AccListQuery;

    public OfflineAccListTableDao(DaoConfig config) {
        super(config);
    }
    
    public OfflineAccListTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"OFFLINE_ACC_LIST_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ACC_ID\" INTEGER," + // 1: accId
                "\"ACC__BAL\" TEXT," + // 2: ACC_BAL
                "\"ACC__NO\" TEXT," + // 3: ACC_NO
                "\"ACC__TYPE\" TEXT," + // 4: ACC_TYPE
                "\"PAYMENT\" TEXT," + // 5: PAYMENT
                "\"TRAN__ID\" TEXT);"); // 6: TRAN_ID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"OFFLINE_ACC_LIST_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OfflineAccListTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long accId = entity.getAccId();
        if (accId != null) {
            stmt.bindLong(2, accId);
        }
 
        String ACC_BAL = entity.getACC_BAL();
        if (ACC_BAL != null) {
            stmt.bindString(3, ACC_BAL);
        }
 
        String ACC_NO = entity.getACC_NO();
        if (ACC_NO != null) {
            stmt.bindString(4, ACC_NO);
        }
 
        String ACC_TYPE = entity.getACC_TYPE();
        if (ACC_TYPE != null) {
            stmt.bindString(5, ACC_TYPE);
        }
 
        String PAYMENT = entity.getPAYMENT();
        if (PAYMENT != null) {
            stmt.bindString(6, PAYMENT);
        }
 
        String TRAN_ID = entity.getTRAN_ID();
        if (TRAN_ID != null) {
            stmt.bindString(7, TRAN_ID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OfflineAccListTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long accId = entity.getAccId();
        if (accId != null) {
            stmt.bindLong(2, accId);
        }
 
        String ACC_BAL = entity.getACC_BAL();
        if (ACC_BAL != null) {
            stmt.bindString(3, ACC_BAL);
        }
 
        String ACC_NO = entity.getACC_NO();
        if (ACC_NO != null) {
            stmt.bindString(4, ACC_NO);
        }
 
        String ACC_TYPE = entity.getACC_TYPE();
        if (ACC_TYPE != null) {
            stmt.bindString(5, ACC_TYPE);
        }
 
        String PAYMENT = entity.getPAYMENT();
        if (PAYMENT != null) {
            stmt.bindString(6, PAYMENT);
        }
 
        String TRAN_ID = entity.getTRAN_ID();
        if (TRAN_ID != null) {
            stmt.bindString(7, TRAN_ID);
        }
    }

    @Override
    protected final void attachEntity(OfflineAccListTable entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OfflineAccListTable readEntity(Cursor cursor, int offset) {
        OfflineAccListTable entity = new OfflineAccListTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // accId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ACC_BAL
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ACC_NO
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // ACC_TYPE
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // PAYMENT
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // TRAN_ID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OfflineAccListTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAccId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setACC_BAL(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setACC_NO(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setACC_TYPE(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPAYMENT(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTRAN_ID(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OfflineAccListTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OfflineAccListTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OfflineAccListTable entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "accList" to-many relationship of OfflineOrderTable. */
    public List<OfflineAccListTable> _queryOfflineOrderTable_AccList(Long accId) {
        synchronized (this) {
            if (offlineOrderTable_AccListQuery == null) {
                QueryBuilder<OfflineAccListTable> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AccId.eq(null));
                offlineOrderTable_AccListQuery = queryBuilder.build();
            }
        }
        Query<OfflineAccListTable> query = offlineOrderTable_AccListQuery.forCurrentThread();
        query.setParameter(0, accId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getOfflineOrderTableDao().getAllColumns());
            builder.append(" FROM OFFLINE_ACC_LIST_TABLE T");
            builder.append(" LEFT JOIN OFFLINE_ORDER_TABLE T0 ON T.\"ACC_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected OfflineAccListTable loadCurrentDeep(Cursor cursor, boolean lock) {
        OfflineAccListTable entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        OfflineOrderTable offlineOrderTable = loadCurrentOther(daoSession.getOfflineOrderTableDao(), cursor, offset);
        entity.setOfflineOrderTable(offlineOrderTable);

        return entity;    
    }

    public OfflineAccListTable loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<OfflineAccListTable> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<OfflineAccListTable> list = new ArrayList<OfflineAccListTable>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<OfflineAccListTable> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<OfflineAccListTable> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
