package com.yannuo.dgcanteen.greendao.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yannuo.dgcanteen.greendao.entity.FacePayTable;

import com.yannuo.dgcanteen.greendao.entity.OfflineOrderTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "OFFLINE_ORDER_TABLE".
*/
public class OfflineOrderTableDao extends AbstractDao<OfflineOrderTable, Long> {

    public static final String TABLENAME = "OFFLINE_ORDER_TABLE";

    /**
     * Properties of entity OfflineOrderTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FacePayId = new Property(1, Long.class, "facePayId", false, "FACE_PAY_ID");
        public final static Property BusinessId = new Property(2, String.class, "businessId", false, "BUSINESS_ID");
        public final static Property BusinessName = new Property(3, String.class, "businessName", false, "BUSINESS_NAME");
        public final static Property CampusId = new Property(4, String.class, "campusId", false, "CAMPUS_ID");
        public final static Property CorpId = new Property(5, String.class, "corpId", false, "CORP_ID");
        public final static Property VposId = new Property(6, String.class, "vposId", false, "VPOS_ID");
        public final static Property DeviceId = new Property(7, String.class, "deviceId", false, "DEVICE_ID");
        public final static Property CustId = new Property(8, String.class, "custId", false, "CUST_ID");
        public final static Property Username = new Property(9, String.class, "username", false, "USERNAME");
        public final static Property PayType = new Property(10, String.class, "payType", false, "PAY_TYPE");
        public final static Property PayContent = new Property(11, String.class, "payContent", false, "PAY_CONTENT");
        public final static Property Payment = new Property(12, String.class, "payment", false, "PAYMENT");
        public final static Property ActualPayment = new Property(13, String.class, "actualPayment", false, "ACTUAL_PAYMENT");
        public final static Property SessionId = new Property(14, String.class, "sessionId", false, "SESSION_ID");
        public final static Property PayDate = new Property(15, String.class, "payDate", false, "PAY_DATE");
        public final static Property SignTime = new Property(16, String.class, "signTime", false, "SIGN_TIME");
        public final static Property Offline = new Property(17, String.class, "offline", false, "OFFLINE");
        public final static Property Flag = new Property(18, Integer.class, "flag", false, "FLAG");
    }

    private DaoSession daoSession;


    public OfflineOrderTableDao(DaoConfig config) {
        super(config);
    }
    
    public OfflineOrderTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"OFFLINE_ORDER_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FACE_PAY_ID\" INTEGER," + // 1: facePayId
                "\"BUSINESS_ID\" TEXT," + // 2: businessId
                "\"BUSINESS_NAME\" TEXT," + // 3: businessName
                "\"CAMPUS_ID\" TEXT," + // 4: campusId
                "\"CORP_ID\" TEXT," + // 5: corpId
                "\"VPOS_ID\" TEXT," + // 6: vposId
                "\"DEVICE_ID\" TEXT," + // 7: deviceId
                "\"CUST_ID\" TEXT," + // 8: custId
                "\"USERNAME\" TEXT," + // 9: username
                "\"PAY_TYPE\" TEXT," + // 10: payType
                "\"PAY_CONTENT\" TEXT," + // 11: payContent
                "\"PAYMENT\" TEXT," + // 12: payment
                "\"ACTUAL_PAYMENT\" TEXT," + // 13: actualPayment
                "\"SESSION_ID\" TEXT UNIQUE ," + // 14: sessionId
                "\"PAY_DATE\" TEXT," + // 15: payDate
                "\"SIGN_TIME\" TEXT," + // 16: signTime
                "\"OFFLINE\" TEXT," + // 17: offline
                "\"FLAG\" INTEGER);"); // 18: flag
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"OFFLINE_ORDER_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OfflineOrderTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long facePayId = entity.getFacePayId();
        if (facePayId != null) {
            stmt.bindLong(2, facePayId);
        }
 
        String businessId = entity.getBusinessId();
        if (businessId != null) {
            stmt.bindString(3, businessId);
        }
 
        String businessName = entity.getBusinessName();
        if (businessName != null) {
            stmt.bindString(4, businessName);
        }
 
        String campusId = entity.getCampusId();
        if (campusId != null) {
            stmt.bindString(5, campusId);
        }
 
        String corpId = entity.getCorpId();
        if (corpId != null) {
            stmt.bindString(6, corpId);
        }
 
        String vposId = entity.getVposId();
        if (vposId != null) {
            stmt.bindString(7, vposId);
        }
 
        String deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindString(8, deviceId);
        }
 
        String custId = entity.getCustId();
        if (custId != null) {
            stmt.bindString(9, custId);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(10, username);
        }
 
        String payType = entity.getPayType();
        if (payType != null) {
            stmt.bindString(11, payType);
        }
 
        String payContent = entity.getPayContent();
        if (payContent != null) {
            stmt.bindString(12, payContent);
        }
 
        String payment = entity.getPayment();
        if (payment != null) {
            stmt.bindString(13, payment);
        }
 
        String actualPayment = entity.getActualPayment();
        if (actualPayment != null) {
            stmt.bindString(14, actualPayment);
        }
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(15, sessionId);
        }
 
        String payDate = entity.getPayDate();
        if (payDate != null) {
            stmt.bindString(16, payDate);
        }
 
        String signTime = entity.getSignTime();
        if (signTime != null) {
            stmt.bindString(17, signTime);
        }
 
        String offline = entity.getOffline();
        if (offline != null) {
            stmt.bindString(18, offline);
        }
 
        Integer flag = entity.getFlag();
        if (flag != null) {
            stmt.bindLong(19, flag);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OfflineOrderTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long facePayId = entity.getFacePayId();
        if (facePayId != null) {
            stmt.bindLong(2, facePayId);
        }
 
        String businessId = entity.getBusinessId();
        if (businessId != null) {
            stmt.bindString(3, businessId);
        }
 
        String businessName = entity.getBusinessName();
        if (businessName != null) {
            stmt.bindString(4, businessName);
        }
 
        String campusId = entity.getCampusId();
        if (campusId != null) {
            stmt.bindString(5, campusId);
        }
 
        String corpId = entity.getCorpId();
        if (corpId != null) {
            stmt.bindString(6, corpId);
        }
 
        String vposId = entity.getVposId();
        if (vposId != null) {
            stmt.bindString(7, vposId);
        }
 
        String deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindString(8, deviceId);
        }
 
        String custId = entity.getCustId();
        if (custId != null) {
            stmt.bindString(9, custId);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(10, username);
        }
 
        String payType = entity.getPayType();
        if (payType != null) {
            stmt.bindString(11, payType);
        }
 
        String payContent = entity.getPayContent();
        if (payContent != null) {
            stmt.bindString(12, payContent);
        }
 
        String payment = entity.getPayment();
        if (payment != null) {
            stmt.bindString(13, payment);
        }
 
        String actualPayment = entity.getActualPayment();
        if (actualPayment != null) {
            stmt.bindString(14, actualPayment);
        }
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(15, sessionId);
        }
 
        String payDate = entity.getPayDate();
        if (payDate != null) {
            stmt.bindString(16, payDate);
        }
 
        String signTime = entity.getSignTime();
        if (signTime != null) {
            stmt.bindString(17, signTime);
        }
 
        String offline = entity.getOffline();
        if (offline != null) {
            stmt.bindString(18, offline);
        }
 
        Integer flag = entity.getFlag();
        if (flag != null) {
            stmt.bindLong(19, flag);
        }
    }

    @Override
    protected final void attachEntity(OfflineOrderTable entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OfflineOrderTable readEntity(Cursor cursor, int offset) {
        OfflineOrderTable entity = new OfflineOrderTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // facePayId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // businessId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // businessName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // campusId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // corpId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // vposId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // deviceId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // custId
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // username
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // payType
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // payContent
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // payment
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // actualPayment
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // sessionId
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // payDate
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // signTime
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // offline
            cursor.isNull(offset + 18) ? null : cursor.getInt(offset + 18) // flag
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OfflineOrderTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFacePayId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setBusinessId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBusinessName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCampusId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCorpId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setVposId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDeviceId(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCustId(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setUsername(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setPayType(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setPayContent(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setPayment(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setActualPayment(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setSessionId(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setPayDate(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setSignTime(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setOffline(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setFlag(cursor.isNull(offset + 18) ? null : cursor.getInt(offset + 18));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OfflineOrderTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OfflineOrderTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OfflineOrderTable entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getFacePayTableDao().getAllColumns());
            builder.append(" FROM OFFLINE_ORDER_TABLE T");
            builder.append(" LEFT JOIN FACE_PAY_TABLE T0 ON T.\"FACE_PAY_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected OfflineOrderTable loadCurrentDeep(Cursor cursor, boolean lock) {
        OfflineOrderTable entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        FacePayTable facePayTable = loadCurrentOther(daoSession.getFacePayTableDao(), cursor, offset);
        entity.setFacePayTable(facePayTable);

        return entity;    
    }

    public OfflineOrderTable loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<OfflineOrderTable> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<OfflineOrderTable> list = new ArrayList<OfflineOrderTable>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<OfflineOrderTable> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<OfflineOrderTable> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
