package com.yannuo.dgcanteen.greendao.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.yannuo.dgcanteen.greendao.entity.PayOrderTable;

import com.yannuo.dgcanteen.greendao.entity.PayDishTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PAY_DISH_TABLE".
*/
public class PayDishTableDao extends AbstractDao<PayDishTable, Long> {

    public static final String TABLENAME = "PAY_DISH_TABLE";

    /**
     * Properties of entity PayDishTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PayOrderId = new Property(1, Long.class, "payOrderId", false, "PAY_ORDER_ID");
        public final static Property DishesId = new Property(2, String.class, "dishesId", false, "DISHES_ID");
        public final static Property DishesName = new Property(3, String.class, "dishesName", false, "DISHES_NAME");
        public final static Property DishesNumber = new Property(4, String.class, "dishesNumber", false, "DISHES_NUMBER");
        public final static Property DishesPrice = new Property(5, String.class, "dishesPrice", false, "DISHES_PRICE");
    }

    private DaoSession daoSession;

    private Query<PayDishTable> payOrderTable_PaymentDishesListQuery;

    public PayDishTableDao(DaoConfig config) {
        super(config);
    }
    
    public PayDishTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PAY_DISH_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PAY_ORDER_ID\" INTEGER," + // 1: payOrderId
                "\"DISHES_ID\" TEXT," + // 2: dishesId
                "\"DISHES_NAME\" TEXT," + // 3: dishesName
                "\"DISHES_NUMBER\" TEXT," + // 4: dishesNumber
                "\"DISHES_PRICE\" TEXT);"); // 5: dishesPrice
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PAY_DISH_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PayDishTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long payOrderId = entity.getPayOrderId();
        if (payOrderId != null) {
            stmt.bindLong(2, payOrderId);
        }
 
        String dishesId = entity.getDishesId();
        if (dishesId != null) {
            stmt.bindString(3, dishesId);
        }
 
        String dishesName = entity.getDishesName();
        if (dishesName != null) {
            stmt.bindString(4, dishesName);
        }
 
        String dishesNumber = entity.getDishesNumber();
        if (dishesNumber != null) {
            stmt.bindString(5, dishesNumber);
        }
 
        String dishesPrice = entity.getDishesPrice();
        if (dishesPrice != null) {
            stmt.bindString(6, dishesPrice);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PayDishTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long payOrderId = entity.getPayOrderId();
        if (payOrderId != null) {
            stmt.bindLong(2, payOrderId);
        }
 
        String dishesId = entity.getDishesId();
        if (dishesId != null) {
            stmt.bindString(3, dishesId);
        }
 
        String dishesName = entity.getDishesName();
        if (dishesName != null) {
            stmt.bindString(4, dishesName);
        }
 
        String dishesNumber = entity.getDishesNumber();
        if (dishesNumber != null) {
            stmt.bindString(5, dishesNumber);
        }
 
        String dishesPrice = entity.getDishesPrice();
        if (dishesPrice != null) {
            stmt.bindString(6, dishesPrice);
        }
    }

    @Override
    protected final void attachEntity(PayDishTable entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PayDishTable readEntity(Cursor cursor, int offset) {
        PayDishTable entity = new PayDishTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // payOrderId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // dishesId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // dishesName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // dishesNumber
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // dishesPrice
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PayDishTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPayOrderId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setDishesId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDishesName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDishesNumber(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDishesPrice(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PayDishTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PayDishTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PayDishTable entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "paymentDishesList" to-many relationship of PayOrderTable. */
    public List<PayDishTable> _queryPayOrderTable_PaymentDishesList(Long payOrderId) {
        synchronized (this) {
            if (payOrderTable_PaymentDishesListQuery == null) {
                QueryBuilder<PayDishTable> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PayOrderId.eq(null));
                payOrderTable_PaymentDishesListQuery = queryBuilder.build();
            }
        }
        Query<PayDishTable> query = payOrderTable_PaymentDishesListQuery.forCurrentThread();
        query.setParameter(0, payOrderId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPayOrderTableDao().getAllColumns());
            builder.append(" FROM PAY_DISH_TABLE T");
            builder.append(" LEFT JOIN PAY_ORDER_TABLE T0 ON T.\"PAY_ORDER_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PayDishTable loadCurrentDeep(Cursor cursor, boolean lock) {
        PayDishTable entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        PayOrderTable payOrderTable = loadCurrentOther(daoSession.getPayOrderTableDao(), cursor, offset);
        entity.setPayOrderTable(payOrderTable);

        return entity;    
    }

    public PayDishTable loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PayDishTable> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PayDishTable> list = new ArrayList<PayDishTable>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PayDishTable> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PayDishTable> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
