package com.yannuo.dgcanteen.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yannuo.dgcanteen.greendao.entity.PayOrderTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PAY_ORDER_TABLE".
*/
public class PayOrderTableDao extends AbstractDao<PayOrderTable, Long> {

    public static final String TABLENAME = "PAY_ORDER_TABLE";

    /**
     * Properties of entity PayOrderTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Result = new Property(1, String.class, "result", false, "RESULT");
        public final static Property TranResult = new Property(2, String.class, "tranResult", false, "TRAN_RESULT");
        public final static Property BusinessId = new Property(3, String.class, "businessId", false, "BUSINESS_ID");
        public final static Property BusinessName = new Property(4, String.class, "businessName", false, "BUSINESS_NAME");
        public final static Property CampusId = new Property(5, String.class, "campusId", false, "CAMPUS_ID");
        public final static Property CorpId = new Property(6, String.class, "corpId", false, "CORP_ID");
        public final static Property VposId = new Property(7, String.class, "vposId", false, "VPOS_ID");
        public final static Property DeviceId = new Property(8, String.class, "deviceId", false, "DEVICE_ID");
        public final static Property CustId = new Property(9, String.class, "custId", false, "CUST_ID");
        public final static Property Username = new Property(10, String.class, "username", false, "USERNAME");
        public final static Property AccNo = new Property(11, String.class, "accNo", false, "ACC_NO");
        public final static Property AccBal = new Property(12, String.class, "accBal", false, "ACC_BAL");
        public final static Property AccType = new Property(13, String.class, "accType", false, "ACC_TYPE");
        public final static Property AccList = new Property(14, String.class, "accList", false, "ACC_LIST");
        public final static Property OrderId = new Property(15, String.class, "orderId", false, "ORDER_ID");
        public final static Property TraceId = new Property(16, String.class, "traceId", false, "TRACE_ID");
        public final static Property PayType = new Property(17, String.class, "payType", false, "PAY_TYPE");
        public final static Property PayContent = new Property(18, String.class, "payContent", false, "PAY_CONTENT");
        public final static Property Payment = new Property(19, String.class, "payment", false, "PAYMENT");
        public final static Property ActualPayment = new Property(20, String.class, "actualPayment", false, "ACTUAL_PAYMENT");
        public final static Property PayTime = new Property(21, String.class, "payTime", false, "PAY_TIME");
        public final static Property PayDate = new Property(22, String.class, "payDate", false, "PAY_DATE");
        public final static Property Offline = new Property(23, String.class, "offline", false, "OFFLINE");
        public final static Property Flag = new Property(24, Integer.class, "flag", false, "FLAG");
    }

    private DaoSession daoSession;


    public PayOrderTableDao(DaoConfig config) {
        super(config);
    }
    
    public PayOrderTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PAY_ORDER_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"RESULT\" TEXT," + // 1: result
                "\"TRAN_RESULT\" TEXT," + // 2: tranResult
                "\"BUSINESS_ID\" TEXT," + // 3: businessId
                "\"BUSINESS_NAME\" TEXT," + // 4: businessName
                "\"CAMPUS_ID\" TEXT," + // 5: campusId
                "\"CORP_ID\" TEXT," + // 6: corpId
                "\"VPOS_ID\" TEXT," + // 7: vposId
                "\"DEVICE_ID\" TEXT," + // 8: deviceId
                "\"CUST_ID\" TEXT," + // 9: custId
                "\"USERNAME\" TEXT," + // 10: username
                "\"ACC_NO\" TEXT," + // 11: accNo
                "\"ACC_BAL\" TEXT," + // 12: accBal
                "\"ACC_TYPE\" TEXT," + // 13: accType
                "\"ACC_LIST\" TEXT," + // 14: accList
                "\"ORDER_ID\" TEXT UNIQUE ," + // 15: orderId
                "\"TRACE_ID\" TEXT," + // 16: traceId
                "\"PAY_TYPE\" TEXT," + // 17: payType
                "\"PAY_CONTENT\" TEXT," + // 18: payContent
                "\"PAYMENT\" TEXT," + // 19: payment
                "\"ACTUAL_PAYMENT\" TEXT," + // 20: actualPayment
                "\"PAY_TIME\" TEXT," + // 21: payTime
                "\"PAY_DATE\" TEXT," + // 22: payDate
                "\"OFFLINE\" TEXT," + // 23: offline
                "\"FLAG\" INTEGER);"); // 24: flag
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PAY_ORDER_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PayOrderTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String result = entity.getResult();
        if (result != null) {
            stmt.bindString(2, result);
        }
 
        String tranResult = entity.getTranResult();
        if (tranResult != null) {
            stmt.bindString(3, tranResult);
        }
 
        String businessId = entity.getBusinessId();
        if (businessId != null) {
            stmt.bindString(4, businessId);
        }
 
        String businessName = entity.getBusinessName();
        if (businessName != null) {
            stmt.bindString(5, businessName);
        }
 
        String campusId = entity.getCampusId();
        if (campusId != null) {
            stmt.bindString(6, campusId);
        }
 
        String corpId = entity.getCorpId();
        if (corpId != null) {
            stmt.bindString(7, corpId);
        }
 
        String vposId = entity.getVposId();
        if (vposId != null) {
            stmt.bindString(8, vposId);
        }
 
        String deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindString(9, deviceId);
        }
 
        String custId = entity.getCustId();
        if (custId != null) {
            stmt.bindString(10, custId);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(11, username);
        }
 
        String accNo = entity.getAccNo();
        if (accNo != null) {
            stmt.bindString(12, accNo);
        }
 
        String accBal = entity.getAccBal();
        if (accBal != null) {
            stmt.bindString(13, accBal);
        }
 
        String accType = entity.getAccType();
        if (accType != null) {
            stmt.bindString(14, accType);
        }
 
        String accList = entity.getAccList();
        if (accList != null) {
            stmt.bindString(15, accList);
        }
 
        String orderId = entity.getOrderId();
        if (orderId != null) {
            stmt.bindString(16, orderId);
        }
 
        String traceId = entity.getTraceId();
        if (traceId != null) {
            stmt.bindString(17, traceId);
        }
 
        String payType = entity.getPayType();
        if (payType != null) {
            stmt.bindString(18, payType);
        }
 
        String payContent = entity.getPayContent();
        if (payContent != null) {
            stmt.bindString(19, payContent);
        }
 
        String payment = entity.getPayment();
        if (payment != null) {
            stmt.bindString(20, payment);
        }
 
        String actualPayment = entity.getActualPayment();
        if (actualPayment != null) {
            stmt.bindString(21, actualPayment);
        }
 
        String payTime = entity.getPayTime();
        if (payTime != null) {
            stmt.bindString(22, payTime);
        }
 
        String payDate = entity.getPayDate();
        if (payDate != null) {
            stmt.bindString(23, payDate);
        }
 
        String offline = entity.getOffline();
        if (offline != null) {
            stmt.bindString(24, offline);
        }
 
        Integer flag = entity.getFlag();
        if (flag != null) {
            stmt.bindLong(25, flag);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PayOrderTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String result = entity.getResult();
        if (result != null) {
            stmt.bindString(2, result);
        }
 
        String tranResult = entity.getTranResult();
        if (tranResult != null) {
            stmt.bindString(3, tranResult);
        }
 
        String businessId = entity.getBusinessId();
        if (businessId != null) {
            stmt.bindString(4, businessId);
        }
 
        String businessName = entity.getBusinessName();
        if (businessName != null) {
            stmt.bindString(5, businessName);
        }
 
        String campusId = entity.getCampusId();
        if (campusId != null) {
            stmt.bindString(6, campusId);
        }
 
        String corpId = entity.getCorpId();
        if (corpId != null) {
            stmt.bindString(7, corpId);
        }
 
        String vposId = entity.getVposId();
        if (vposId != null) {
            stmt.bindString(8, vposId);
        }
 
        String deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindString(9, deviceId);
        }
 
        String custId = entity.getCustId();
        if (custId != null) {
            stmt.bindString(10, custId);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(11, username);
        }
 
        String accNo = entity.getAccNo();
        if (accNo != null) {
            stmt.bindString(12, accNo);
        }
 
        String accBal = entity.getAccBal();
        if (accBal != null) {
            stmt.bindString(13, accBal);
        }
 
        String accType = entity.getAccType();
        if (accType != null) {
            stmt.bindString(14, accType);
        }
 
        String accList = entity.getAccList();
        if (accList != null) {
            stmt.bindString(15, accList);
        }
 
        String orderId = entity.getOrderId();
        if (orderId != null) {
            stmt.bindString(16, orderId);
        }
 
        String traceId = entity.getTraceId();
        if (traceId != null) {
            stmt.bindString(17, traceId);
        }
 
        String payType = entity.getPayType();
        if (payType != null) {
            stmt.bindString(18, payType);
        }
 
        String payContent = entity.getPayContent();
        if (payContent != null) {
            stmt.bindString(19, payContent);
        }
 
        String payment = entity.getPayment();
        if (payment != null) {
            stmt.bindString(20, payment);
        }
 
        String actualPayment = entity.getActualPayment();
        if (actualPayment != null) {
            stmt.bindString(21, actualPayment);
        }
 
        String payTime = entity.getPayTime();
        if (payTime != null) {
            stmt.bindString(22, payTime);
        }
 
        String payDate = entity.getPayDate();
        if (payDate != null) {
            stmt.bindString(23, payDate);
        }
 
        String offline = entity.getOffline();
        if (offline != null) {
            stmt.bindString(24, offline);
        }
 
        Integer flag = entity.getFlag();
        if (flag != null) {
            stmt.bindLong(25, flag);
        }
    }

    @Override
    protected final void attachEntity(PayOrderTable entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PayOrderTable readEntity(Cursor cursor, int offset) {
        PayOrderTable entity = new PayOrderTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // result
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // tranResult
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // businessId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // businessName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // campusId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // corpId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // vposId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // deviceId
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // custId
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // username
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // accNo
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // accBal
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // accType
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // accList
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // orderId
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // traceId
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // payType
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // payContent
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // payment
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // actualPayment
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // payTime
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // payDate
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // offline
            cursor.isNull(offset + 24) ? null : cursor.getInt(offset + 24) // flag
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PayOrderTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setResult(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTranResult(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBusinessId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBusinessName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCampusId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCorpId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setVposId(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDeviceId(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCustId(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setUsername(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setAccNo(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setAccBal(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setAccType(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setAccList(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setOrderId(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setTraceId(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setPayType(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setPayContent(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setPayment(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setActualPayment(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setPayTime(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setPayDate(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setOffline(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setFlag(cursor.isNull(offset + 24) ? null : cursor.getInt(offset + 24));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PayOrderTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PayOrderTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PayOrderTable entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
