package com.yannuo.dgcanteen.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yannuo.dgcanteen.greendao.entity.UserFaceData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_FACE_DATA".
*/
public class UserFaceDataDao extends AbstractDao<UserFaceData, Long> {

    public static final String TABLENAME = "USER_FACE_DATA";

    /**
     * Properties of entity UserFaceData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CustId = new Property(1, String.class, "custId", false, "CUST_ID");
        public final static Property UserId = new Property(2, String.class, "userId", false, "USER_ID");
        public final static Property CampusId = new Property(3, String.class, "campusId", false, "CAMPUS_ID");
        public final static Property Eigenvalue = new Property(4, String.class, "eigenvalue", false, "EIGENVALUE");
        public final static Property Way = new Property(5, String.class, "way", false, "WAY");
        public final static Property FaceImgUrl = new Property(6, String.class, "faceImgUrl", false, "FACE_IMG_URL");
        public final static Property Version = new Property(7, String.class, "version", false, "VERSION");
        public final static Property CreateTime = new Property(8, String.class, "createTime", false, "CREATE_TIME");
        public final static Property UpdateTime = new Property(9, String.class, "updateTime", false, "UPDATE_TIME");
    }


    public UserFaceDataDao(DaoConfig config) {
        super(config);
    }
    
    public UserFaceDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_FACE_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CUST_ID\" TEXT UNIQUE ," + // 1: custId
                "\"USER_ID\" TEXT UNIQUE ," + // 2: userId
                "\"CAMPUS_ID\" TEXT," + // 3: campusId
                "\"EIGENVALUE\" TEXT UNIQUE ," + // 4: eigenvalue
                "\"WAY\" TEXT," + // 5: way
                "\"FACE_IMG_URL\" TEXT," + // 6: faceImgUrl
                "\"VERSION\" TEXT," + // 7: version
                "\"CREATE_TIME\" TEXT," + // 8: createTime
                "\"UPDATE_TIME\" TEXT);"); // 9: updateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_FACE_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserFaceData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String custId = entity.getCustId();
        if (custId != null) {
            stmt.bindString(2, custId);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(3, userId);
        }
 
        String campusId = entity.getCampusId();
        if (campusId != null) {
            stmt.bindString(4, campusId);
        }
 
        String eigenvalue = entity.getEigenvalue();
        if (eigenvalue != null) {
            stmt.bindString(5, eigenvalue);
        }
 
        String way = entity.getWay();
        if (way != null) {
            stmt.bindString(6, way);
        }
 
        String faceImgUrl = entity.getFaceImgUrl();
        if (faceImgUrl != null) {
            stmt.bindString(7, faceImgUrl);
        }
 
        String version = entity.getVersion();
        if (version != null) {
            stmt.bindString(8, version);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(9, createTime);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(10, updateTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserFaceData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String custId = entity.getCustId();
        if (custId != null) {
            stmt.bindString(2, custId);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(3, userId);
        }
 
        String campusId = entity.getCampusId();
        if (campusId != null) {
            stmt.bindString(4, campusId);
        }
 
        String eigenvalue = entity.getEigenvalue();
        if (eigenvalue != null) {
            stmt.bindString(5, eigenvalue);
        }
 
        String way = entity.getWay();
        if (way != null) {
            stmt.bindString(6, way);
        }
 
        String faceImgUrl = entity.getFaceImgUrl();
        if (faceImgUrl != null) {
            stmt.bindString(7, faceImgUrl);
        }
 
        String version = entity.getVersion();
        if (version != null) {
            stmt.bindString(8, version);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(9, createTime);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(10, updateTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserFaceData readEntity(Cursor cursor, int offset) {
        UserFaceData entity = new UserFaceData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // custId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // userId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // campusId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // eigenvalue
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // way
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // faceImgUrl
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // version
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // createTime
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // updateTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserFaceData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCustId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCampusId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setEigenvalue(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setWay(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFaceImgUrl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setVersion(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCreateTime(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setUpdateTime(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserFaceData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserFaceData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserFaceData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
